(()=>{const D=window.GUIDE_DATA;const $=(s,r=document)=>r.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let route=location.hash.replace('#/','')||'home';
function img(url,cap=''){return `<figure class="photo"><img src="${url}" alt="${esc(cap)}" loading="lazy"><figcaption>${esc(cap)}</figcaption></figure>`}
function block(b){if(b.h)return `<section class="prose"><h2>${esc(b.h)}</h2>${b.p?`<p>${esc(b.p)}</p>`:''}${b.list?`<ul>${b.list.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</section>`;
if(b.gallery)return `<div class="gallery">${b.gallery.map(x=>img(x[0],x[1])).join('')}</div>`;
if(b.timeline)return `<div class="timeline">${b.timeline.map(x=>`<article><time>${esc(x[0])}</time><div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div></article>`).join('')}</div>`;
if(b.animals)return `<div class="animal-grid">${b.animals.map(a=>`<article class="animal"><img src="${a[1]}" alt="${esc(a[0])}" loading="lazy"><div><h3>${esc(a[0])}</h3><em>${esc(a[2])}</em><p>${esc(a[3])}</p></div></article>`).join('')}</div>`;return ''}
function shell(content){return `<aside class="side"><div class="brand"><span>PERU</span><b>2026</b><small>EXPEDITION FIELD GUIDE</small></div><nav>${D.nav.map(n=>`<button data-r="${n[0]}" class="${route===n[0]?'on':''}">${n[1]}</button>`).join('')}</nav><a class="private" href="${D.privateNotion}" target="_blank" rel="noreferrer">🔐 Prywatny sejf Notion</a></aside><main>${content}</main><button class="menu">☰</button>`}
function home(){return `<header class="cover" style="background-image:linear-gradient(180deg,rgba(0,0,0,.15),rgba(0,0,0,.82)),url('${D.photos.hero}')"><div><p>PERU • 04–26.09.2026</p><h1>Expedition<br>Field Guide</h1><h2>Kuba · Weronika · Daniel</h2><button data-r="plan">Otwórz plan wyprawy</button></div></header><section class="intro"><p class="lead">Dokumentalny przewodnik po miejscach, które naprawdę odwiedzicie — z historią, realnymi zdjęciami, mapowym myśleniem i instrukcjami terenowymi.</p><div class="feature-grid">${[['machu','Machu Picchu','Ruta 3-A + przewodnik po 2-A/2-B'],['amazon','Amazonia','Curassow 6D/5N i atlas terenowy'],['sacred','Sacred Valley','Pisac, Moray, Maras, Chinchero'],['cusco','Cusco','Stolica Tawantinsuyu']].map(x=>`<button data-r="${x[0]}"><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}</div></section>`}
function page(id){const s=D.sections.find(x=>x.id===id);if(!s)return home();return `<header class="chapter-hero" style="background-image:linear-gradient(180deg,rgba(0,0,0,.2),rgba(0,0,0,.85)),url('${s.hero}')"><div><p>${esc(s.kicker)}</p><h1>${esc(s.title)}</h1></div></header><article class="chapter"><p class="lead">${esc(s.intro)}</p>${s.blocks.map(block).join('')}<p class="backtop"><a href="#">Wróć na górę ↑</a></p></article>`}
function render(){document.body.innerHTML=`<div id="app">${shell(route==='home'?home():page(route))}</div><div id="lightbox" class="lightbox" hidden><button>×</button><img alt=""><p></p></div>`;document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{route=b.dataset.r;location.hash='#/'+route;render();scrollTo(0,0)});$('.menu').onclick=()=>$('.side').classList.toggle('open');document.querySelectorAll('.photo img,.animal img').forEach(i=>i.onclick=()=>{const l=$('#lightbox');l.hidden=false;$('img',l).src=i.src;$('p',l).textContent=i.alt});$('#lightbox button').onclick=()=>$('#lightbox').hidden=true;}
addEventListener('hashchange',()=>{route=location.hash.replace('#/','')||'home';render()});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');})();