window.PERU_2026 = {
  meta: {
    title: "Peru 2026",
    subtitle: "Expedition Command",
    travelers: "Kuba · Weronika · Daniel",
    dates: "04–26.09.2026",
    startDate: "2026-09-04T00:00:00+02:00",
    privacy: "Publiczna wersja nie zawiera kodów rezerwacji, dokładnych adresów, telefonu kontaktowego ani konkretnych kwot.",
    notion: "",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Machu%20Picchu%2C%20Peru.jpg?width=1800"
  },
  status: {
    done: { label: "Zrobione", tone: "green" },
    confirmed: { label: "Potwierdzone", tone: "green" },
    buy: { label: "Do rezerwacji", tone: "amber" },
    open: { label: "Decyzja otwarta", tone: "red" },
    onsite: { label: "Na miejscu", tone: "blue" },
    planned: { label: "Plan ustalony", tone: "slate" }
  },
  route: [
    ["Lima", "04–07.09"],
    ["Iquitos", "07.09"],
    ["Curassow", "07–12.09"],
    ["Iquitos", "12–14.09"],
    ["Cusco", "14–17.09"],
    ["Sacred Valley", "17.09"],
    ["Ollantaytambo", "17–19.09"],
    ["Aguas Calientes", "19–20.09"],
    ["Machu Picchu", "20.09"],
    ["Lima", "21–26.09"]
  ],
  bookings: [
    { id:"lima-start", name:"Lima — pierwszy nocleg", date:"04–07.09", detail:"Airbnb w Miraflores dostępne przed nocnymi i porannymi przylotami.", status:"done", supplier:"Airbnb", payment:"paid", settlement:"pending" },
    { id:"lim-iqt", name:"Lot Lima → Iquitos", date:"07.09 · 07:15–09:05", detail:"Star Peru. Bagaż nadawany i podręczny są uwzględnione.", status:"done", supplier:"Star Peru", payment:"paid", settlement:"pending" },
    { id:"curassow", name:"Curassow Amazon Lodge", date:"07–12.09 · 6D/5N", detail:"Odbiór z lotniska w Iquitos. Po wyprawie odstawienie pod nocleg około 16:00.", status:"confirmed", supplier:"Curassow Amazon Lodge", payment:"partial", settlement:"pending" },
    { id:"iquitos", name:"Iquitos — nocleg po dżungli", date:"12–14.09", detail:"Airbnb na prysznic, pranie, przepakowanie i spokojny dzień po Amazonii.", status:"done", supplier:"Airbnb", payment:"paid", settlement:"pending" },
    { id:"iqt-cuz", name:"Lot Iquitos → Lima → Cusco", date:"14.09 · 07:20–12:50", detail:"SKY, jedna rezerwacja. W Iquitos sprawdzić oznaczenie bagażu do CUZ.", status:"done", supplier:"SKY", payment:"paid", settlement:"pending" },
    { id:"machu3a", name:"Machu Picchu — Ruta 3-A", date:"20.09 · 07:00", detail:"Circuito 3 — Realeza + Montaña Waynapicchu, dla całej trójki.", status:"done", supplier:"Ministerio de Cultura", payment:"paid", settlement:"pending" },
    { id:"train-out", name:"Pociąg Ollantaytambo → Aguas", date:"19.09 · 12:55", detail:"PeruRail Expedition. Na stacji najpóźniej o 12:25.", status:"done", supplier:"PeruRail", payment:"paid", settlement:"pending" },
    { id:"cusco-hotel", name:"Hotel w Cusco", date:"14–17.09", detail:"Spokojna lokalizacja, bez stromego podejścia, dobre ogrzewanie i ciepła woda.", status:"buy", supplier:"Do wyboru", payment:"unpaid", settlement:"none" },
    { id:"taxidatum", name:"Prywatny TaxiDatum — Sacred Valley", date:"17.09", detail:"Cusco → Pisac Ruins → Pisac Market → Moray → Maras → Chinchero → Ollantaytambo.", status:"buy", supplier:"TaxiDatum", payment:"unpaid", settlement:"none" },
    { id:"olla-hotel", name:"Hotel w Ollantaytambo", date:"17–19.09", detail:"Musi przechować duże plecaki od 19.09 do wieczora 20.09.", status:"buy", supplier:"Do wyboru", payment:"unpaid", settlement:"none" },
    { id:"olla-buffer", name:"Anulowalna noc w Ollantaytambo", date:"20–21.09", detail:"Zabezpieczenie pod rekomendowany pociąg o 20:50.", status:"buy", supplier:"Do wyboru", payment:"unpaid", settlement:"none" },
    { id:"aguas-hotel", name:"Hotel w Aguas Calientes", date:"19–20.09", detail:"Cicho, blisko autobusów i stacji; przechowanie małych plecaków po wymeldowaniu.", status:"buy", supplier:"Do wyboru", payment:"unpaid", settlement:"none" },
    { id:"train-back", name:"Pociąg Aguas → Ollantaytambo", date:"20.09", detail:"18:20 jest szybszy, ale ryzykowny. 20:50 jest wariantem rekomendowanym.", status:"open", supplier:"PeruRail / Inca Rail", payment:"unpaid", settlement:"none" },
    { id:"cuz-lim", name:"Lot Cusco → Lima", date:"21.09", detail:"Przy noclegu w Ollantaytambo wybierać popołudnie, najlepiej nie wcześniej niż 14:00–15:00.", status:"buy", supplier:"Do wyboru", payment:"unpaid", settlement:"none" },
    { id:"lima-end", name:"Końcowy nocleg w Limie", date:"21–26.09", detail:"Miraflores lub Barranco. Daniel i Weronika do 25.09, Kuba do 26.09.", status:"buy", supplier:"Do wyboru", payment:"unpaid", settlement:"none" }
  ],
  itinerary: [
    { date:"04.09", place:"Lima", title:"Start rezerwacji mieszkania", status:"done", sleep:"Airbnb Lima", transport:"—", body:"Mieszkanie jest dostępne już od 04.09, dzięki czemu można wejść bez czekania po nocnych i porannych przylotach." },
    { date:"05.09", place:"Lima", title:"Przylot Kuby i Daniela", status:"confirmed", sleep:"Airbnb Lima", transport:"Lotnisko → Miraflores: większy Uber/Cabify lub oficjalna taxi", body:"Kuba przylatuje o 01:45, Daniel o 04:25. Po bagażu przejazd do Miraflores, sen, jedzenie i zero presji na zwiedzanie." },
    { date:"06.09", place:"Lima", title:"Przylot Weroniki i regeneracja", status:"confirmed", sleep:"Airbnb Lima", transport:"Lotnisko → Miraflores", body:"Weronika przylatuje o 06:30 po około 30 godzinach podróży. Cały dzień jest przeznaczony na regenerację. Miraflores lub Barranco tylko przy realnej energii." },
    { date:"07.09", place:"Lima → Iquitos → Amazonia", title:"Lot i start Curassow", status:"confirmed", sleep:"Curassow Amazon Lodge", transport:"Wyjazd z Airbnb najpóźniej 04:00; lot 07:15–09:05", body:"Zamówić XL/SUV/van około 03:40–03:45. Na lotnisku celować w 04:45–05:00. Po odebraniu plecaków spotkanie z ekipą Curassow i transfer do lodge." },
    { date:"08.09", place:"Amazonia", title:"Curassow — dzień terenowy", status:"confirmed", sleep:"Curassow", transport:"Łódź / canoe / pieszo", body:"Program zależny od pogody, poziomu wody i aktywności zwierząt. Priorytetem jest praca z prywatnym przewodnikiem, nie sztywny rozkład godzin." },
    { date:"09.09", place:"Amazonia", title:"Curassow — dzień terenowy", status:"confirmed", sleep:"Curassow", transport:"Łódź / canoe / pieszo", body:"Wczesne wyjścia, obserwacja zwierząt, eksploracja rzek i lasu. Konkretna kolejność może zostać zmieniona przez przewodnika." },
    { date:"10.09", place:"Amazonia", title:"Curassow — dzień terenowy", status:"confirmed", sleep:"Curassow", transport:"Łódź / canoe / pieszo", body:"Kontynuacja programu, możliwy pierwotny las, survival, nocne wyjście lub przygotowanie do campingu — zależnie od programu operacyjnego." },
    { date:"11.09", place:"Amazonia", title:"Curassow — camping / noc terenowa", status:"confirmed", sleep:"Curassow lub obóz", transport:"Pieszo / łódź", body:"Najbardziej terenowa część programu. Ostateczny przebieg zależy od warunków i decyzji przewodnika." },
    { date:"12.09", place:"Amazonia → Iquitos", title:"Koniec wyprawy i reset", status:"confirmed", sleep:"Airbnb Iquitos", transport:"Curassow odstawia pod nocleg około 16:00", body:"Prysznic, normalne jedzenie, pranie i odpoczynek. Bez dalszego programu obowiązkowego." },
    { date:"13.09", place:"Iquitos", title:"Spokojny dzień po dżungli", status:"planned", sleep:"Airbnb Iquitos", transport:"Pieszo / krótka taxi", body:"Pranie, przepakowanie, promenada i centrum, spokojne jedzenie. Bez ciężkiego zwiedzania." },
    { date:"14.09", place:"Iquitos → Lima → Cusco", title:"Lot i początek aklimatyzacji", status:"buy", sleep:"Cusco — do rezerwacji", transport:"Taxi 04:40; lot 07:20; przylot Cusco 12:50", body:"Wyjazd około 04:45, lotnisko około 05:15. Przy nadawaniu upewnić się, że bagaż jest oznaczony do CUZ. Po przylocie tylko hotel, jedzenie i odpoczynek." },
    { date:"15.09", place:"Cusco", title:"Spokojne centrum", status:"planned", sleep:"Cusco", transport:"Pieszo / taxi przy zmęczeniu", body:"Plaza de Armas, San Blas, Mercado San Pedro, dużo przerw i wolne tempo. Bez ścigania listy atrakcji." },
    { date:"16.09", place:"Cusco", title:"Drugi dzień aklimatyzacji", status:"planned", sleep:"Cusco", transport:"Pieszo / taxi", body:"Lekki program dopasowany do samopoczucia. Bez całodniowego forsowania organizmu na wysokości." },
    { date:"17.09", place:"Sacred Valley", title:"Prywatny przejazd do Ollantaytambo", status:"buy", sleep:"Ollantaytambo — do rezerwacji", transport:"TaxiDatum — prywatny samochód", body:"Plan: Pisac Ruins → Pisac Market → Moray → Maras/Salineras → Chinchero → Ollantaytambo. Kolejność i realną wykonalność potwierdzić z kierowcą." },
    { date:"18.09", place:"Ollantaytambo", title:"Ruiny i stare miasteczko", status:"planned", sleep:"Ollantaytambo", transport:"Pieszo", body:"Ruiny, zachowany układ ulic, widoki, kawa i spokojny dzień. Bez gonienia przed Machu Picchu." },
    { date:"19.09", place:"Ollantaytambo → Aguas Calientes", title:"Pociąg i próba zakupu Ruty 2", status:"onsite", sleep:"Aguas Calientes — do rezerwacji", transport:"PeruRail 12:55–około 14:25", body:"Duże plecaki zostają w hotelu w Ollantaytambo. Na stacji o 12:25. Po przyjeździe szybkie zostawienie małych plecaków i kolejka do Centro Cultural z paszportami." },
    { date:"20.09", place:"Machu Picchu", title:"Waynapicchu + możliwa Ruta 2", status:"open", sleep:"Ollantaytambo lub Cusco", transport:"Bus Aguas ↔ Machu + pociąg powrotny", body:"Wejście Ruta 3-A o 07:00. Druga Ruta 2 najlepiej o 13:00, następnie 14:00. Pociąg 20:50 jest rekomendowany, ponieważ zabezpiecza opóźnienia i późniejsze wejście." },
    { date:"21.09", place:"Ollantaytambo / Cusco → Lima", title:"Transfer i lot", status:"buy", sleep:"Lima — do rezerwacji", transport:"Taxi na lotnisko + lot do Limy", body:"Bez zwiedzania. Przy noclegu w Ollantaytambo taxi bezpośrednio na lotnisko i lot po południu. Przy noclegu w Cusco można lecieć wcześniej." },
    { date:"22.09", place:"Lima", title:"Pełny dzień odpoczynku", status:"planned", sleep:"Lima", transport:"Pieszo / taxi", body:"Jedzenie, spacer, ewentualnie basen lub rooftop. Żadnego obowiązkowego programu." },
    { date:"23.09", place:"Lima", title:"Miraflores lub Barranco", status:"planned", sleep:"Lima", transport:"Pieszo / taxi", body:"Luźny dzień: spacer, dobre jedzenie albo całkowity odpoczynek." },
    { date:"24.09", place:"Lima", title:"Ostatni wspólny pełny dzień", status:"planned", sleep:"Lima", transport:"Pieszo / taxi", body:"Bez presji. Pakowanie i wspólna kolacja." },
    { date:"25.09", place:"Lima", title:"Wyloty Daniela i Weroniki", status:"open", sleep:"Lima — tylko Kuba", transport:"Transfery zależne od końcowego hotelu", body:"Daniel wylot 09:40, Weronika 12:00. Kuba zostaje jedną dodatkową noc." },
    { date:"26.09", place:"Lima → Europa", title:"Wylot Kuby", status:"planned", sleep:"—", transport:"Transfer na lotnisko", body:"Wylot o 09:25. Godzinę wyjazdu ustalić po wyborze końcowego hotelu i ponownym sprawdzeniu warunków drogowych." }
  ],
  tasks: [
    { id:"t1", title:"Zarezerwować hotel w Cusco", when:"14–17.09", note:"Spokojna lokalizacja, bez stromego podejścia, dobra ciepła woda i anulowanie.", status:"buy" },
    { id:"t2", title:"Zarezerwować hotel w Ollantaytambo", when:"17–19.09", note:"Musi przechować duże plecaki do wieczora 20.09.", status:"buy" },
    { id:"t3", title:"Zarezerwować anulowalną noc w Ollantaytambo", when:"20–21.09", note:"Zabezpieczenie pod pociąg 20:50.", status:"buy" },
    { id:"t4", title:"Zarezerwować nocleg w Aguas Calientes", when:"19–20.09", note:"Blisko autobusów i stacji; przechowanie bagaży po wymeldowaniu.", status:"buy" },
    { id:"t5", title:"Zarezerwować TaxiDatum na Sacred Valley", when:"17.09", note:"Pisac Ruins, Pisac Market, Moray, Maras, Chinchero, zakończenie w Ollantaytambo.", status:"buy" },
    { id:"t6", title:"Kupić lot Cusco → Lima", when:"21.09", note:"Przy starcie z Ollantaytambo najlepiej nie wcześniej niż 14:00–15:00.", status:"buy" },
    { id:"t7", title:"Zarezerwować końcową Limę", when:"21–26.09", note:"Daniel i Weronika do 25.09; Kuba do 26.09.", status:"buy" },
    { id:"t8", title:"Wybrać godzinę pociągu powrotnego", when:"20.09", note:"18:20 tylko przy odpowiednio wczesnej Rucie 2 i sprawnym zjeździe; 20:50 rekomendowany.", status:"open" },
    { id:"t9", title:"Kupić pociąg Aguas → Ollantaytambo", when:"20.09", note:"Nie kupować do Cusco, ponieważ duże plecaki zostają w Ollantaytambo.", status:"buy" },
    { id:"t10", title:"Ustalić taxi Ollantaytambo → Cusco / lotnisko", when:"20 lub 21.09", note:"Zależne od wybranego pociągu i noclegu.", status:"open" },
    { id:"t11", title:"Kupić autobus Aguas ↔ Machu Picchu", when:"Do 19.09", note:"Online kilka dni wcześniej albo po przyjeździe.", status:"buy" },
    { id:"t12", title:"Spróbować kupić Rutę 2", when:"19.09 na miejscu", note:"Priorytet: 13:00, potem 14:00. 2A przed 2B tylko przy tej samej godzinie.", status:"onsite" },
    { id:"t13", title:"Opłacić pozostałe saldo Curassow", when:"Przed wyprawą w Iquitos", note:"Depozyt jest opłacony; reszta pozostaje do zapłaty.", status:"buy" },
    { id:"t14", title:"Ustalić końcowe transfery w Limie", when:"25–26.09", note:"Dopiero po wyborze końcowego hotelu.", status:"open" }
  ],
  machu19: [
    ["12:25", "Stacja Ollantaytambo", "Stawić się na stacji. Duże plecaki zostają w hotelu; do Aguas jadą tylko małe plecaki."],
    ["12:55–14:25", "PeruRail Expedition", "Kupiony przejazd do Machu Picchu Pueblo."],
    ["14:25–14:45", "Szybki check-in", "Zostawić bagaże. Nie planować obiadu ani spaceru."],
    ["około 14:45", "Kolejka do Centro Cultural", "Cała trójka z oryginalnymi paszportami. Procedurę i godziny sprawdzić ponownie przed podróżą."],
    ["od 15:00", "Zakup Ruty 2", "Kolejność próśb: 2A 13:00 → 2B 13:00 → 2A/2B 14:00 → 15:00 awaryjnie."],
    ["po zakupie", "Hotel i przygotowanie", "Bus, mały plecak zgodny z limitem, dokumenty, woda, lekkie warstwy i porządne śniadanie."]
  ],
  machu20: [
    ["05:00–05:25", "Pobudka i śniadanie", "Zjeść porządnie. Zabrać dokumenty, wodę, lekką kurtkę i mały plecak."],
    ["05:30–05:50", "Wyjście do autobusów", "Nie zostawiać tego na ostatnią chwilę. Bilet autobusowy mieć wcześniej."],
    ["około 06:00–06:30", "Autobus w górę", "Przejazd zwykle około 25–30 minut. Po przyjeździe toaleta i kolejka."],
    ["07:00", "Wejście Ruta 3-A", "Circuito 3 — Realeza, Montaña Waynapicchu. Cała trójka wchodzi razem."],
    ["07:30–10:30", "Waynapicchu", "Podejście, widoki i zejście. Bez forsowania tempa kosztem bezpieczeństwa."],
    ["10:30–11:30/12:00", "Dokończenie Ruty 3-A", "Realny cel wyjścia około 11:15–11:45; 12:00 nadal mieści się w planie."],
    ["11:15–12:40", "Przerwa poza bramkami", "Toaleta, odpoczynek i szybkie jedzenie przy wejściu. Nie zjeżdżać do Aguas przed wejściem 13:00."],
    ["13:00 lub 14:00", "Drugie wejście — Ruta 2", "13:00 najlepsze. 14:00 nadal dobre, ale praktycznie oznacza pociąg 20:50."],
    ["po wyjściu", "Autobus do Aguas", "Kolejka i zjazd mogą zająć 40–70 minut. Odebrać bagaże, zjeść i być na stacji minimum 30 minut wcześniej."],
    ["18:20 lub 20:50", "Pociąg do Ollantaytambo", "18:20 szybszy, lecz ryzykowny. 20:50 rekomendowany i odporniejszy na opóźnienia."]
  ],
  scenarios: [
    { name:"Brak Ruty 2", action:"Po Waynapicchu spokojny lunch w Aguas. Pociąg 18:20 jest łatwy, ale można zachować 20:50 dla pełnego spokoju." },
    { name:"Ruta 2 o 13:00", action:"18:20 jest możliwy bez długiego obiadu i przy sprawnym autobusie. 20:50 eliminuje presję." },
    { name:"Ruta 2 o 14:00 lub 15:00", action:"Nie planować pociągu 18:20. Brać 20:50 i nocleg w Ollantaytambo." },
    { name:"Waynapicchu kończy się około 12:00", action:"Ruta 2 o 13:00 nadal może się udać, ale przerwa będzie bardzo krótka. Jedzenie przy wejściu." },
    { name:"Długi zjazd autobusem", action:"Wariant 20:50 pochłania większość problemów. Na 18:20 nie liczyć, jeżeli około 17:00 nie jesteście już w Aguas." }
  ],
  payments: [
    { name:"Airbnb Lima 04–07.09", supplier:"Zapłacone", payer:"Daniel", settlement:"Do rozliczenia" },
    { name:"Lot Lima → Iquitos", supplier:"Zapłacone", payer:"Kuba", settlement:"Do rozliczenia" },
    { name:"Depozyt Curassow", supplier:"Zapłacone", payer:"Kuba", settlement:"Do rozliczenia" },
    { name:"Pozostałe saldo Curassow", supplier:"Niezapłacone", payer:"—", settlement:"Do rozliczenia po płatności" },
    { name:"Airbnb Iquitos 12–14.09", supplier:"Zapłacone", payer:"Daniel", settlement:"Do rozliczenia" },
    { name:"Lot Iquitos → Lima → Cusco", supplier:"Zapłacone", payer:"Kuba", settlement:"Do rozliczenia" },
    { name:"Machu Picchu — Ruta 3-A", supplier:"Zapłacone", payer:"Daniel", settlement:"Do rozliczenia" },
    { name:"Pociąg Ollantaytambo → Aguas", supplier:"Zapłacone", payer:"Kuba", settlement:"Do rozliczenia" },
    { name:"Hotele Cusco / Ollantaytambo / Aguas / Lima", supplier:"Niezapłacone", payer:"—", settlement:"Do rozliczenia po rezerwacji" },
    { name:"TaxiDatum Sacred Valley", supplier:"Niezapłacone", payer:"—", settlement:"Do rozliczenia po płatności" },
    { name:"Pociąg Aguas → Ollantaytambo", supplier:"Niezapłacone", payer:"—", settlement:"Do rozliczenia po zakupie" },
    { name:"Lot Cusco → Lima", supplier:"Niezapłacone", payer:"—", settlement:"Do rozliczenia po zakupie" }
  ],
  chapters: [
    { id:"amazon", title:"Amazonia i Curassow", scope:"Ekologia lasu, rzeki, program 6D/5N, camping, fauna, bezpieczeństwo i obserwacja zwierząt.", stage:"Etap 2" },
    { id:"iquitos", title:"Iquitos i epoka kauczuku", scope:"Miasto, historia kauczuku, przemoc kolonialna, architektura i spacer po centrum.", stage:"Etap 2" },
    { id:"cusco", title:"Cusco", scope:"Tawantinsuyu, kolonialne nakładanie miasta, przewodnik terenowy i aklimatyzacja.", stage:"Etap 2" },
    { id:"sacred", title:"Sacred Valley", scope:"Pisac, Moray, Maras, Chinchero oraz logika całego dnia TaxiDatum.", stage:"Etap 2" },
    { id:"olla", title:"Ollantaytambo", scope:"Twierdza, miasto, tarasy, Świątynia Słońca, spichlerze i spacer krok po kroku.", stage:"Etap 2" },
    { id:"machu", title:"Machu Picchu i Waynapicchu", scope:"Pełna historia, archeologia, Ruta 3-A, Ruta 2-A/2-B, budowle, hipotezy i przewodnik fotograficzny.", stage:"Etap 2" },
    { id:"wildlife", title:"Fauna Amazonii", scope:"Rozbudowane profile gatunków, tropy, zachowanie, szanse spotkania i fotografowanie.", stage:"Etap 3" },
    { id:"flora", title:"Flora Amazonii i Andów", scope:"Drzewa, palmy, rośliny wodne, epifity, rośliny użytkowe i ich ekologia.", stage:"Etap 3" },
    { id:"food", title:"Jedzenie i napoje", scope:"Co zamawiać, jak smakuje, pochodzenie, bezpieczeństwo i prawdziwe zdjęcia dań.", stage:"Etap 3" }
  ]
};
