(() => {
  const L = (pl, en, es) => ({ pl, en, es });
  const S = (time, title, text) => ({ time, title, text });
  window.PERU_DAY_DETAILS = {
    version: 18,
    days: {
      '04.09': {
        kicker: L('Dzień techniczny', 'Technical day', 'Día técnico'),
        lead: L('Mieszkanie zaczyna się dzień wcześniej, aby nocne przyloty nie kończyły się czekaniem pod drzwiami. To nie jest dzień zwiedzania, tylko zabezpieczenie całej operacji.', 'The apartment starts one day early so the night arrivals do not end with waiting outside. This is not a sightseeing day; it protects the whole operation.', 'El alojamiento empieza un día antes para que las llegadas nocturnas no terminen esperando en la calle. No es un día de turismo, sino una medida operativa.'),
        schedule: [
          S('przed wyjazdem', L('Sprawdzenie dostępu', 'Access check', 'Comprobar acceso'), L('Potwierdzić instrukcję wejścia, godziny check-in i sposób kontaktu w razie problemu.', 'Confirm entry instructions, check-in hours and the contact method in case of a problem.', 'Confirmar instrucciones de entrada, horario de check-in y contacto en caso de problema.')),
          S('wieczór', L('Dokumenty offline', 'Offline documents', 'Documentos sin conexión'), L('Zapisać adres prywatnie, mapę dojazdu i potwierdzenie na co najmniej dwóch telefonach.', 'Save the private address, route map and confirmation on at least two phones.', 'Guardar la dirección privada, el mapa y la confirmación en al menos dos teléfonos.')),
          S('noc', L('Mieszkanie pozostaje puste', 'Apartment remains empty', 'El alojamiento queda vacío'), L('To celowy koszt kupujący spokój dla przylotów 05.09.', 'This deliberate cost buys certainty for the arrivals on 5 September.', 'Es un coste deliberado que compra tranquilidad para las llegadas del 5 de septiembre.'))
        ],
        historyTitle: L('Dlaczego Lima stała się bramą Peru', 'Why Lima became Peru’s gateway', 'Por qué Lima se convirtió en la puerta del Perú'),
        history: [
          L('Lima została założona przez Hiszpanów w 1535 roku jako Ciudad de los Reyes. Jej położenie przy wybrzeżu i blisko portu Callao uczyniło ją administracyjnym oraz handlowym centrum kolonialnego Wicekrólestwa Peru.', 'Lima was founded by the Spanish in 1535 as Ciudad de los Reyes. Its coastal position and proximity to Callao made it the administrative and commercial centre of the colonial Viceroyalty of Peru.', 'Lima fue fundada por los españoles en 1535 como Ciudad de los Reyes. Su ubicación costera y la cercanía del Callao la convirtieron en centro administrativo y comercial del virreinato.'),
          L('Dzisiejsza rola lotniczego węzła jest kontynuacją tej centralizacji. Większość międzynarodowych podróży do Peru zaczyna się właśnie tutaj, nawet gdy głównym celem są Amazonia albo Andy.', 'Its modern role as an air hub continues that centralisation. Most international journeys to Peru begin here, even when the real destination is the Amazon or the Andes.', 'Su papel moderno como centro aéreo continúa esa centralización. La mayoría de los viajes internacionales al Perú empiezan aquí, aunque el destino real sea la Amazonía o los Andes.')
        ],
        practical: [L('Nie publikować dokładnego adresu Airbnb w publicznej aplikacji.', 'Do not publish the exact Airbnb address in the public app.', 'No publicar la dirección exacta del Airbnb en la app pública.'), L('Instrukcję wejścia trzymać również jako zrzut ekranu.', 'Keep the entry instructions as screenshots too.', 'Guardar también capturas de las instrucciones de entrada.'), L('Ten dzień nie wymaga osobnej aktywności ani transportu.', 'This day requires no separate activity or transport.', 'Este día no necesita actividad ni transporte.')],
        chapter: 'lima', media: { category:'Lima', target:'malecon' }
      },
      '05.09': {
        kicker: L('Przylot i reset', 'Arrival and reset', 'Llegada y descanso'),
        lead: L('Kuba i Daniel lądują w nocy i nad ranem. Najważniejsze są bezpieczny przejazd, wejście do mieszkania, sen i pierwszy spokojny posiłek.', 'Kuba and Daniel land during the night and early morning. The priorities are a safe transfer, getting into the apartment, sleep and a calm first meal.', 'Kuba y Daniel llegan de noche y de madrugada. Las prioridades son el traslado seguro, entrar al alojamiento, dormir y comer con calma.'),
        schedule: [
          S('01:45', L('Przylot Kuby', 'Kuba arrives', 'Llega Kuba'), L('Po bagażu zamówić większy samochód z oficjalnej strefy odbioru.', 'After baggage claim, order a larger car from the official pickup zone.', 'Tras recoger el equipaje, pedir un coche grande desde la zona oficial.')),
          S('04:25', L('Przylot Daniela', 'Daniel arrives', 'Llega Daniel'), L('Ustalić wcześniej, czy Kuba wraca na lotnisko, czy Daniel jedzie sam do mieszkania.', 'Decide in advance whether Kuba returns to the airport or Daniel travels alone to the apartment.', 'Decidir antes si Kuba vuelve al aeropuerto o Daniel va solo al alojamiento.')),
          S('południe', L('Sen, jedzenie, spacer tylko opcjonalnie', 'Sleep, food, optional walk only', 'Dormir, comer y paseo opcional'), L('Nie nadrabiać miasta. Krótki Malecón tylko wtedy, gdy obaj macie realną energię.', 'Do not try to “catch up” on the city. A short Malecón walk only if both genuinely have energy.', 'No intentar “recuperar” la ciudad. Paseo corto por el Malecón solo si ambos tienen energía real.'))
        ],
        historyTitle: L('Lima nad Pacyfikiem', 'Lima on the Pacific', 'Lima frente al Pacífico'),
        history: [
          L('Lima nie leży bezpośrednio w tropikalnym, zielonym krajobrazie, którego można oczekiwać na tej szerokości geograficznej. Chłodny Prąd Peruwiański i pustynne wybrzeże tworzą klimat z częstą mgłą garúa oraz niewielkimi opadami.', 'Lima does not sit in the lush tropical landscape one might expect at this latitude. The cold Peruvian Current and the coastal desert create frequent garúa mist and very little rainfall.', 'Lima no se encuentra en el paisaje tropical verde que cabría esperar a esta latitud. La corriente fría peruana y el desierto costero producen la garúa y muy poca lluvia.'),
          L('Miraflores jest współczesną, wygodną bazą podróżną, ale nie reprezentuje całego miasta. To uporządkowana dzielnica na klifach, powiązana z resztą wielomilionowej metropolii znacznie bardziej chaotyczną siecią ulic i dzielnic.', 'Miraflores is a convenient modern travel base, but it does not represent the whole city. It is an organised district on the cliffs within a far more complex metropolis.', 'Miraflores es una base moderna y cómoda, pero no representa toda la ciudad. Es un distrito ordenado sobre los acantilados dentro de una metrópoli mucho más compleja.')
        ],
        practical: [L('Na lotnisku używać oficjalnej taxi albo aplikacji z uzgodnionym punktem odbioru.', 'Use an official taxi or an app with a confirmed pickup point at the airport.', 'Usar taxi oficial o una app con punto de recogida acordado.'), L('Nie planować rezerwacji restauracji na konkretną godzinę.', 'Do not book a restaurant for a fixed time.', 'No reservar restaurante a una hora fija.'), L('Wodę i prosty posiłek kupić blisko mieszkania.', 'Buy water and a simple meal near the apartment.', 'Comprar agua y comida sencilla cerca del alojamiento.')],
        chapter: 'lima', media: { category:'Lima', target:'malecon' }
      },
      '06.09': {
        kicker: L('Regeneracja Weroniki', 'Weronika recovery day', 'Día de recuperación de Weronika'),
        lead: L('Po około 30 godzinach podróży Weronika potrzebuje dnia bez presji. Cała grupa dostosowuje rytm do osoby najbardziej zmęczonej.', 'After roughly 30 hours of travel, Weronika needs a pressure-free day. The whole group follows the pace of the most tired person.', 'Después de unas 30 horas de viaje, Weronika necesita un día sin presión. Todo el grupo adapta el ritmo a la persona más cansada.'),
        schedule: [
          S('06:30', L('Przylot Weroniki', 'Weronika arrives', 'Llega Weronika'), L('Odbiór, bagaż, spokojny przejazd do mieszkania.', 'Meet her, collect baggage and travel calmly to the apartment.', 'Recogerla, recoger el equipaje y viajar con calma al alojamiento.')),
          S('rano–popołudnie', L('Sen i pełny reset', 'Sleep and full reset', 'Dormir y recuperarse'), L('Zasłonić okna, zjeść coś lekkiego i pozwolić organizmowi zejść z napięcia podróży.', 'Darken the room, eat something light and let the body come down from travel stress.', 'Oscurecer la habitación, comer algo ligero y dejar que el cuerpo se recupere del viaje.')),
          S('wieczór', L('Krótki spacer albo kolacja', 'Short walk or dinner', 'Paseo corto o cena'), L('Barranco lub Malecón tylko jako miękka opcja, nie obowiązek.', 'Barranco or the Malecón only as a soft option, never an obligation.', 'Barranco o el Malecón solo como opción suave, nunca como obligación.'))
        ],
        historyTitle: L('Miraflores przed Miraflores', 'Miraflores before modern Miraflores', 'Miraflores antes del Miraflores moderno'),
        history: [
          L('Teren dzisiejszej Limy był zamieszkany na długo przed Inkami i Hiszpanami. Huaca Pucllana, wznoszona przez kulturę Lima około V–VIII wieku, przypomina, że nowoczesna dzielnica stoi na znacznie starszym krajobrazie ceremonialnym.', 'The area of modern Lima was inhabited long before the Inca and Spanish periods. Huaca Pucllana, built by the Lima culture around the fifth to eighth centuries, shows that the modern district rests on a much older ceremonial landscape.', 'El territorio de la Lima actual estuvo habitado mucho antes de los incas y españoles. Huaca Pucllana, construida por la cultura Lima entre los siglos V y VIII, muestra que el distrito moderno se alza sobre un paisaje ceremonial mucho más antiguo.'),
          L('Miraflores rozwinęło się jako nadmorska dzielnica mieszkaniowa i handlowa. Dziś jego bezpieczeństwo, restauracje i położenie przy klifach sprawiają, że jest najłatwiejszą bazą dla pierwszych dni w Peru.', 'Miraflores developed as a coastal residential and commercial district. Its relative safety, restaurants and cliffside setting now make it the easiest base for the first days in Peru.', 'Miraflores se desarrolló como distrito residencial y comercial costero. Su seguridad relativa, restaurantes y ubicación sobre los acantilados lo convierten en una base sencilla para los primeros días.')
        ],
        practical: [L('Nie przesuwać snu Weroniki na siłę, żeby „ustawić zegar”.', 'Do not force Weronika to stay awake just to “reset the clock”.', 'No obligar a Weronika a mantenerse despierta solo para “ajustar el reloj”.'), L('Spakować część rzeczy na lot do Iquitos już wieczorem.', 'Pack part of the luggage for Iquitos in the evening.', 'Preparar por la noche parte del equipaje para Iquitos.'), L('Ustawić dwa alarmy na bardzo wczesny wyjazd 07.09.', 'Set two alarms for the very early departure on 7 September.', 'Poner dos alarmas para la salida muy temprana del 7 de septiembre.')],
        chapter: 'lima', media: { category:'Lima', target:'huaca' }
      },
      '07.09': {
        kicker: L('Zmiana świata w jeden poranek', 'A complete change of world in one morning', 'Cambio total de mundo en una mañana'),
        lead: L('W kilka godzin przechodzicie z pustynnego wybrzeża do wilgotnej Amazonii. Dzień jest logistyczny, ale już po spotkaniu z Curassow zaczyna się właściwa ekspedycja.', 'Within a few hours you move from the desert coast to humid Amazonia. The day is logistical, but the expedition begins as soon as you meet the Curassow team.', 'En pocas horas pasáis de la costa desértica a la Amazonía húmeda. El día es logístico, pero la expedición empieza al encontrar al equipo de Curassow.'),
        schedule: [
          S('03:40–04:00', L('Wyjazd z Miraflores', 'Leave Miraflores', 'Salir de Miraflores'), L('Samochód XL/SUV/van, komplet bagażu i margines na nocne zamknięcia dróg.', 'Use an XL/SUV/van, check all luggage and keep margin for night road closures.', 'Usar XL/SUV/van, revisar equipaje y dejar margen por cierres nocturnos.')),
          S('07:15–09:05', L('Lot Lima → Iquitos', 'Flight Lima → Iquitos', 'Vuelo Lima → Iquitos'), L('W samolocie nawodnienie; po lądowaniu nie rozdzielać się do chwili spotkania z operatorem.', 'Hydrate on the flight; after landing, stay together until meeting the operator.', 'Hidratarse durante el vuelo; tras aterrizar, permanecer juntos hasta encontrar al operador.')),
          S('po 09:05', L('Transfer do Curassow', 'Transfer to Curassow', 'Traslado a Curassow'), L('Przepakowanie, łódź i pierwsze wprowadzenie do programu. Plan może zmienić się wraz z pogodą i poziomem wody.', 'Repack, board the boat and receive the first briefing. Weather and water levels may change the programme.', 'Reorganizar equipaje, subir a la lancha y recibir la primera explicación. El tiempo y el nivel del agua pueden cambiar el programa.'))
        ],
        historyTitle: L('Iquitos: miasto bez drogi', 'Iquitos: a city without a road', 'Iquitos: una ciudad sin carretera'),
        history: [
          L('Iquitos jest największym miastem świata, do którego nie prowadzi zwykłe połączenie drogowe z krajową siecią. Jego rozwój zawsze zależał od rzek i później od lotnictwa.', 'Iquitos is the world’s largest city without a conventional road connection to the national network. Its development has always depended on rivers and later aviation.', 'Iquitos es la ciudad más grande del mundo sin conexión vial convencional con la red nacional. Su desarrollo siempre dependió de los ríos y después de la aviación.'),
          L('W XIX wieku port urósł dzięki żegludze i boomowi kauczukowemu. Bogactwo widoczne w historycznych fasadach miało jednak brutalne zaplecze: eksploatację pracowników oraz przemoc wobec ludności rdzennej.', 'In the nineteenth century the port grew through steam navigation and the rubber boom. The wealth visible in old façades had a brutal foundation: labour exploitation and violence against Indigenous peoples.', 'En el siglo XIX el puerto creció gracias a la navegación y al auge del caucho. La riqueza visible en las fachadas históricas tuvo una base brutal: explotación laboral y violencia contra pueblos indígenas.')
        ],
        practical: [L('Do małego worka: paszport, telefon, powerbank, repelent i sucha warstwa.', 'In a small bag: passport, phone, power bank, repellent and one dry layer.', 'En una bolsa pequeña: pasaporte, teléfono, batería, repelente y una capa seca.'), L('Wszystko elektroniczne zabezpieczyć przed deszczem jeszcze przed wejściem do łodzi.', 'Waterproof all electronics before boarding the boat.', 'Proteger toda la electrónica antes de subir a la lancha.'), L('Od razu powiedzieć przewodnikowi, że priorytetem są zwierzęta, teren i nocne wyjścia.', 'Tell the guide immediately that wildlife, field time and night outings are priorities.', 'Decir desde el principio que las prioridades son fauna, campo y salidas nocturnas.')],
        chapter: 'amazon', media: { category:'Amazonia i Iquitos', target:'curassow' }
      },
      '08.09': {
        kicker: L('Rzeka jako droga', 'The river as a road', 'El río como camino'),
        lead: L('Pierwszy pełny dzień ma nauczyć was poruszania się po Amazonii: ciszy na łodzi, obserwacji brzegów i czytania sygnałów przewodnika.', 'The first full day should teach you how to move through Amazonia: silence on the boat, reading the banks and following the guide’s signals.', 'El primer día completo debe enseñaros a moveros por la Amazonía: silencio en la lancha, lectura de las orillas y señales del guía.'),
        schedule: [S('świt', L('Pierwsza obserwacja', 'First observation outing', 'Primera observación'), L('Ptaki, małpy i aktywność nad wodą przed największym upałem.', 'Birds, monkeys and river activity before the strongest heat.', 'Aves, monos y actividad del río antes del calor fuerte.')), S('dzień', L('Canoe lub marsz', 'Canoe or walk', 'Canoa o caminata'), L('Wolne tempo, przystanki na nasłuchiwanie i nauka podstawowych środowisk.', 'Move slowly, stop to listen and learn the main habitat types.', 'Avanzar despacio, parar para escuchar y aprender los principales hábitats.')), S('zmierzch', L('Druga zmiana lasu', 'The forest’s second shift', 'El segundo turno del bosque'), L('Powrót na wodę lub skraj lasu, gdy aktywność ponownie rośnie.', 'Return to the water or forest edge as activity rises again.', 'Volver al agua o al borde del bosque cuando aumenta otra vez la actividad.'))],
        historyTitle: L('Amazonia nie jest „dziką pustką”', 'Amazonia is not an “empty wilderness”', 'La Amazonía no es un “vacío salvaje”'),
        history: [L('Lasy Amazonii były użytkowane i kształtowane przez ludzi od tysięcy lat. Społeczności rozwijały wiedzę o roślinach, rybach, glebach i sezonowych zmianach rzek, pozostawiając ślady znacznie subtelniejsze niż kamienne miasta Andów.', 'Amazonian forests have been used and shaped by people for thousands of years. Communities developed deep knowledge of plants, fish, soils and seasonal rivers, leaving subtler traces than Andean stone cities.', 'Los bosques amazónicos fueron usados y transformados por personas durante milenios. Las comunidades desarrollaron profundos conocimientos de plantas, peces, suelos y ríos estacionales, dejando huellas más sutiles que las ciudades de piedra andinas.'), L('Rzeka jest jednocześnie drogą, spiżarnią i kalendarzem. Zmiana poziomu wody decyduje o tym, gdzie można dopłynąć, łowić, polować i zakładać ogrody.', 'The river is road, pantry and calendar at once. Water levels determine where people can travel, fish, hunt and cultivate.', 'El río es camino, despensa y calendario al mismo tiempo. El nivel del agua determina dónde se puede viajar, pescar, cazar y cultivar.')],
        practical: [L('Na łodzi nie przekładać gwałtownie ciężaru.', 'Do not shift weight suddenly in the boat.', 'No mover el peso bruscamente en la lancha.'), L('Gdy przewodnik podnosi rękę, natychmiast przestać mówić.', 'When the guide raises a hand, stop talking immediately.', 'Cuando el guía levante la mano, dejar de hablar inmediatamente.'), L('Zapisać pierwsze obserwacje w Wildlife Trackerze wraz z godziną i środowiskiem.', 'Log first sightings with time and habitat in the Wildlife Tracker.', 'Registrar los primeros avistamientos con hora y hábitat.')],
        chapter: 'amazon', media: { category:'Amazonia i Iquitos', target:'canoe' }
      },
      '09.09': {
        kicker: L('Las trójwymiarowy', 'A three-dimensional forest', 'Un bosque tridimensional'),
        lead: L('Drugi pełny dzień koncentruje się na zwierzętach. Najważniejsze jest zrozumienie, że większość życia znajduje się nad wami, za liśćmi albo aktywuje się o innej porze.', 'The second full day focuses on wildlife. Most life is above you, behind leaves or active at a different time.', 'El segundo día completo se centra en la fauna. La mayor parte de la vida está encima, detrás de hojas o activa a otra hora.'),
        schedule: [S('świt', L('Naczelne i ptaki', 'Primates and birds', 'Primates y aves'), L('Słuchać nawoływań i obserwować poruszenie koron.', 'Listen for calls and watch movement in the canopy.', 'Escuchar llamadas y observar movimiento en las copas.')), S('południe', L('Odpoczynek i identyfikacja', 'Rest and identification', 'Descanso e identificación'), L('Przejrzeć zdjęcia i potwierdzić gatunki z przewodnikiem.', 'Review photographs and confirm species with the guide.', 'Revisar fotos y confirmar especies con el guía.')), S('noc', L('Nocne wyjście', 'Night outing', 'Salida nocturna'), L('Płazy, owady, kajmany i nocne ptaki; ręce z dala od pni i szczelin.', 'Amphibians, insects, caimans and nocturnal birds; keep hands away from trunks and crevices.', 'Anfibios, insectos, caimanes y aves nocturnas; manos lejos de troncos y grietas.'))],
        historyTitle: L('Dlaczego europejski wzrok gubi zwierzęta', 'Why an unfamiliar eye misses animals', 'Por qué una mirada inexperta pierde animales'),
        history: [L('Przyrodnicy i lokalni przewodnicy nie tylko patrzą lepiej — czytają zestaw sygnałów: głosy alarmowe, spadające owoce, zapach, świeże ślady i reakcje innych zwierząt. To wiedza budowana przez długie przebywanie w konkretnym środowisku.', 'Naturalists and local guides do not merely “see better”; they read alarm calls, falling fruit, smell, fresh tracks and other animals’ reactions. This knowledge comes from prolonged experience in a specific environment.', 'Naturalistas y guías locales no solo “ven mejor”; leen alarmas, frutos que caen, olores, huellas frescas y reacciones de otros animales. Ese conocimiento nace de mucha experiencia en un entorno concreto.'), L('W historii eksploracji Amazonii lokalna wiedza bywała przedstawiana jako odkrycie przybyszy. W praktyce wiele wypraw naukowych i handlowych zależało od przewodników, wioślarzy oraz społeczności, które znały teren.', 'In the history of Amazonian exploration, local knowledge was often presented as outsiders’ discovery. In reality, expeditions depended on guides, boatmen and communities who knew the terrain.', 'En la historia de la exploración amazónica, el conocimiento local fue presentado muchas veces como descubrimiento externo. En realidad, las expediciones dependían de guías, remeros y comunidades que conocían el terreno.')],
        practical: [L('Najpierw zobaczyć zwierzę, dopiero potem walczyć z aparatem.', 'See the animal first; only then fight with the camera.', 'Primero ver al animal; después pelear con la cámara.'), L('Nie rozdzielać grupy dla lepszego kadru.', 'Do not split the group for a better photograph.', 'No separar el grupo por una foto mejor.'), L('Nie wpisywać gatunku jako pewnego, gdy przewodnik nie potwierdzi identyfikacji.', 'Do not mark a species as certain until the guide confirms it.', 'No marcar una especie como segura hasta que el guía la confirme.')],
        chapter: 'amazon', media: { category:'Amazonia i Iquitos', target:'wildlife' }
      },
      '10.09': {
        kicker: L('Las jako system', 'The forest as a system', 'El bosque como sistema'),
        lead: L('Ten dzień warto przeznaczyć na dłuższy marsz, rośliny, glebę i to, czego nie widać z łodzi. Celem nie jest liczba kilometrów.', 'Use this day for a longer walk, plants, soils and what cannot be seen from a boat. Distance is not the goal.', 'Este día sirve para una caminata más larga, plantas, suelos y lo que no se ve desde la lancha. La distancia no es el objetivo.'),
        schedule: [S('rano', L('Marsz w lesie', 'Forest walk', 'Caminata en el bosque'), L('Wolno, z przystankami przy korzeniach podporowych, śladach żerowania i roślinach użytkowych.', 'Move slowly, stopping at buttress roots, feeding signs and useful plants.', 'Avanzar despacio, parando en raíces, rastros de alimentación y plantas útiles.')), S('południe', L('Rozmowa o roślinach', 'Plants and uses', 'Plantas y usos'), L('Pytać o lokalne nazwy, zastosowania i granice bezpiecznego dotykania.', 'Ask about local names, uses and what is safe to touch.', 'Preguntar nombres locales, usos y qué se puede tocar con seguridad.')), S('wieczór', L('Plan campingu', 'Camping plan', 'Plan de campamento'), L('Potwierdzić miejsce, sprzęt, pogodę i procedurę przy odwołaniu.', 'Confirm location, gear, weather and the cancellation procedure.', 'Confirmar lugar, equipo, tiempo y procedimiento de cancelación.'))],
        historyTitle: L('Kauczuk, botanika i globalny handel', 'Rubber, botany and global trade', 'Caucho, botánica y comercio mundial'),
        history: [L('Kauczukowiec brazylijski rósł naturalnie w Amazonii, a lateks był znany miejscowym społecznościom przed europejskim boomem. W XIX wieku popyt przemysłowy przekształcił rozproszony surowiec w globalny towar.', 'The rubber tree grew naturally in Amazonia and its latex was known locally before the European boom. In the nineteenth century industrial demand turned a dispersed forest resource into a global commodity.', 'El árbol del caucho crecía de forma natural en la Amazonía y su látex era conocido localmente antes del auge europeo. En el siglo XIX la demanda industrial lo convirtió en mercancía global.'), L('Wywiezienie nasion i rozwój plantacji w Azji osłabiły amazoński monopol. Historia pokazuje, jak botanika, kolonialne sieci i przemoc gospodarcza łączyły odległy las z fabrykami na innych kontynentach.', 'The export of seeds and development of Asian plantations broke the Amazonian monopoly. Botany, colonial networks and economic violence linked this forest to factories on other continents.', 'La exportación de semillas y el desarrollo de plantaciones asiáticas rompieron el monopolio amazónico. La botánica, las redes coloniales y la violencia económica conectaron este bosque con fábricas de otros continentes.')],
        practical: [L('Nie dotykać roślin bez zgody przewodnika.', 'Do not touch plants without the guide’s approval.', 'No tocar plantas sin permiso del guía.'), L('Sprawdzić stopy, otarcia i mokre ubrania po powrocie.', 'Check feet, chafing and wet clothing after returning.', 'Revisar pies, rozaduras y ropa mojada al volver.'), L('Jedną suchą warstwę zachować wyłącznie do spania.', 'Keep one dry layer exclusively for sleeping.', 'Reservar una capa seca exclusivamente para dormir.')],
        chapter: 'amazon', media: { category:'Rośliny', target:'rubber-tree' }
      },
      '11.09': {
        kicker: L('Noc terenowa', 'Field night', 'Noche de campo'),
        lead: L('Najbardziej surowy etap pobytu. Sukcesem nie jest cierpienie, lecz pozostanie w lesie po zmroku przy zachowaniu dyscypliny i bezpieczeństwa.', 'The roughest part of the stay. Success is not suffering; it is remaining in the forest after dark with discipline and safety.', 'La parte más dura de la estancia. El éxito no es sufrir, sino permanecer en el bosque después del anochecer con disciplina y seguridad.'),
        schedule: [S('rano', L('Przygotowanie sprzętu', 'Prepare gear', 'Preparar equipo'), L('Tylko potrzebne rzeczy, sucha warstwa, moskitiera, czołówka i zabezpieczona elektronika.', 'Take only essentials: dry layer, mosquito net, headlamp and protected electronics.', 'Llevar solo lo necesario: capa seca, mosquitera, frontal y electrónica protegida.')), S('popołudnie', L('Dojście do obozu', 'Reach camp', 'Llegar al campamento'), L('Obserwować wybór miejsca i sposób organizacji obozu.', 'Observe how the guide selects and organises the camp.', 'Observar cómo el guía elige y organiza el campamento.')), S('noc', L('Słuchanie zmiany lasu', 'Listen to the forest change', 'Escuchar el cambio del bosque'), L('Nie oddalać się samemu. Jedzenie zamknięte, buty i czołówka zawsze w tym samym miejscu.', 'Never walk off alone. Keep food sealed and shoes and headlamp in the same place.', 'No alejarse solo. Comida cerrada, zapatos y frontal siempre en el mismo lugar.'))],
        historyTitle: L('Obóz jako sposób poznania, nie pokaz odwagi', 'Camping as a way of learning, not proving courage', 'Acampar para comprender, no para demostrar valentía'),
        history: [L('Przez tysiące lat noc w lesie była normalną częścią przemieszczania się, polowania, handlu i odwiedzin między osadami. Nowoczesny turysta doświadcza jej jako przygody, lecz dla lokalnych mieszkańców była elementem praktycznej wiedzy.', 'For thousands of years, nights in the forest were a normal part of travel, hunting, trade and visiting between settlements. Tourists experience it as adventure; locally it was practical knowledge.', 'Durante milenios, pasar la noche en el bosque formó parte normal de viajes, caza, comercio y visitas entre comunidades. Para el turista es aventura; localmente era conocimiento práctico.'), L('Warto zwracać uwagę nie tylko na odgłosy zwierząt, lecz na organizację obozu: wybór suchego miejsca, kontrolę ognia i jedzenia, moskitiery oraz orientację w terenie.', 'Notice not only animal sounds but camp organisation: dry ground, control of fire and food, mosquito nets and orientation.', 'Conviene observar no solo los sonidos de animales, sino la organización: suelo seco, control del fuego y comida, mosquiteras y orientación.')],
        practical: [L('Buty wytrząsnąć przed każdym założeniem.', 'Shake shoes before putting them on.', 'Sacudir los zapatos antes de ponérselos.'), L('Nie pozostawiać otwartych opakowań po jedzeniu.', 'Leave no food packaging open.', 'No dejar envases de comida abiertos.'), L('Odwołanie campingu przez przewodnika oznacza dobrą decyzję bezpieczeństwa, nie porażkę.', 'A guide’s cancellation means sound safety judgement, not failure.', 'Si el guía cancela, es una buena decisión de seguridad, no un fracaso.')],
        chapter: 'amazon', media: { category:'Amazonia i Iquitos', target:'forest' }
      },
      '12.09': {
        kicker: L('Powrót do miasta', 'Return to the city', 'Regreso a la ciudad'),
        lead: L('Po zakończeniu programu celem jest odzyskanie komfortu: prysznic, pranie, pełny posiłek i suszenie sprzętu. Nie dokładamy atrakcji.', 'After the programme, recover comfort: shower, laundry, full meal and drying gear. No extra attractions.', 'Al terminar el programa, recuperar comodidad: ducha, lavandería, comida completa y secar equipo. Sin atracciones extra.'),
        schedule: [S('rano', L('Ostatnia aktywność', 'Final activity', 'Última actividad'), L('Nie próbować na siłę „zdobyć” brakującego gatunku.', 'Do not force a final attempt to “collect” a missing species.', 'No forzar un último intento para “conseguir” una especie.')), S('około 16:00', L('Odstawienie pod nocleg', 'Drop-off at accommodation', 'Llegada al alojamiento'), L('Najpierw kontrola bagażu i mokrej elektroniki, potem prysznic.', 'Check luggage and wet electronics before showering.', 'Primero revisar equipaje y electrónica húmeda; luego ducharse.')), S('wieczór', L('Reset', 'Reset', 'Recuperación'), L('Pranie, normalne jedzenie i kopia obserwacji z Wildlife Trackera.', 'Laundry, normal food and a backup of Wildlife Tracker observations.', 'Lavandería, comida normal y copia de las observaciones del tracker.'))],
        historyTitle: L('Lodge i współczesna turystyka przyrodnicza', 'Lodges and modern nature tourism', 'Lodges y turismo de naturaleza moderno'),
        history: [L('Lodge łączy dwa światy: dostęp do odległego środowiska i oczekiwanie podróżnika dotyczące łóżka, łazienki oraz organizacji. Jego wartość zależy mniej od luksusu niż od lokalizacji i jakości przewodników.', 'A lodge connects remote nature with travellers’ expectations of a bed, bathroom and organisation. Its value depends less on luxury than on location and guides.', 'Un lodge conecta naturaleza remota con expectativas de cama, baño y organización. Su valor depende menos del lujo que de la ubicación y los guías.'), L('Turystyka może finansować pracę lokalną oraz ochronę, ale może też upraszczać kulturę i obiecywać nierealne spotkania ze zwierzętami. Warto oceniać ją po uczciwości programu, zachowaniu dystansu do fauny i warunkach pracy zespołu.', 'Tourism can support local jobs and conservation, but it can also simplify culture and promise unrealistic wildlife encounters. Judge it by programme honesty, distance from animals and staff conditions.', 'El turismo puede apoyar empleo y conservación, pero también simplificar culturas y prometer encuentros irreales. Hay que juzgarlo por honestidad, distancia con la fauna y condiciones del personal.')],
        practical: [L('Rozłożyć mokre rzeczy natychmiast, zanim zamkniecie je ponownie w plecaku.', 'Spread wet gear immediately before packing it again.', 'Extender lo mojado inmediatamente antes de volver a guardarlo.'), L('Skontrolować otarcia, ukąszenia i stan stóp.', 'Check chafing, bites and feet.', 'Revisar rozaduras, picaduras y pies.'), L('Nie planować wieczornego wyjścia wymagającego rezerwacji.', 'Do not schedule an evening activity requiring a reservation.', 'No programar una actividad nocturna con reserva.')],
        chapter: 'amazon', media: { category:'Amazonia i Iquitos', target:'bungalow' }
      },
      '13.09': {
        kicker: L('Iquitos bez pośpiechu', 'Iquitos without rushing', 'Iquitos sin prisa'),
        lead: L('Spokojny dzień między Amazonką a Andami. Możecie zobaczyć nabrzeże i centrum, ale najważniejsze pozostaje pranie, przepakowanie i odpoczynek.', 'A calm day between Amazonia and the Andes. You may see the waterfront and centre, but laundry, repacking and rest remain the priority.', 'Día tranquilo entre la Amazonía y los Andes. Podéis ver el malecón y el centro, pero la prioridad sigue siendo lavar, reorganizar y descansar.'),
        schedule: [S('rano', L('Pranie i sprzęt', 'Laundry and gear', 'Lavandería y equipo'), L('Wysuszyć wszystko przed chłodniejszym Cusco.', 'Dry everything before cooler Cusco.', 'Secar todo antes del Cusco más frío.')), S('popołudnie', L('Promenada i centrum', 'Waterfront and centre', 'Malecón y centro'), L('Krótki spacer, fasady z epoki kauczuku i obserwacja życia rzecznego.', 'Short walk, rubber-boom façades and river life.', 'Paseo corto, fachadas del caucho y vida del río.')), S('wieczór', L('Pakowanie do Cusco', 'Pack for Cusco', 'Preparar Cusco'), L('Ciepła warstwa na wierzchu, dokumenty i śniadanie na bardzo wczesny wyjazd.', 'Keep a warm layer accessible, documents ready and breakfast for the early departure.', 'Dejar capa cálida accesible, documentos listos y desayuno para la salida temprana.'))],
        historyTitle: L('Boom kauczukowy: fasady i przemoc', 'The rubber boom: façades and violence', 'El auge del caucho: fachadas y violencia'),
        history: [L('Na przełomie XIX i XX wieku kauczuk przyniósł Iquitos nagłe bogactwo. Importowano metalowe elementy, płytki i europejskie wzory architektoniczne, aby pokazać kosmopolityczny charakter miasta.', 'Around 1900 rubber brought sudden wealth to Iquitos. Metalwork, tiles and European styles were imported to project a cosmopolitan image.', 'Hacia 1900 el caucho trajo riqueza repentina a Iquitos. Se importaron metales, azulejos y estilos europeos para proyectar una imagen cosmopolita.'), L('Za dekoracyjnymi fasadami krył się system przymusu i zadłużenia, szczególnie brutalny wobec ludów rdzennych w regionie Putumayo. Nie należy oglądać architektury boomu bez pamięci o koszcie, który jej nie widać.', 'Behind decorative façades was a coercive debt system, especially brutal toward Indigenous peoples in the Putumayo region. The architecture should not be viewed without remembering that hidden cost.', 'Detrás de las fachadas había un sistema coercitivo de deuda, especialmente brutal contra pueblos indígenas del Putumayo. La arquitectura no debe verse sin recordar ese coste oculto.')],
        practical: [L('W porcie i na targach telefon trzymać dyskretnie.', 'Keep the phone discreet at the port and markets.', 'Mantener el teléfono discreto en puerto y mercados.'), L('Nie fotografować ludzi z bliska bez zgody.', 'Do not photograph people closely without permission.', 'No fotografiar personas de cerca sin permiso.'), L('Przed snem sprawdzić oznaczenie lotu i limit bagażu SKY.', 'Before bed, check the SKY flight and baggage allowance.', 'Antes de dormir, revisar vuelo SKY y equipaje.')],
        chapter: 'iquitos', media: { category:'Amazonia i Iquitos', target:'port' }
      },
      '14.09': {
        kicker: L('Z nizin na 3400 metrów', 'From lowlands to 3,400 metres', 'De las tierras bajas a 3.400 metros'),
        lead: L('To największa fizjologiczna zmiana wyjazdu. Po przylocie do Cusco nie zwiedzacie — organizm ma wykonać pracę adaptacyjną.', 'This is the trip’s biggest physiological change. After landing in Cusco, you do not sightsee; the body needs to adapt.', 'Es el mayor cambio fisiológico del viaje. Tras llegar a Cusco no se hace turismo; el cuerpo necesita adaptarse.'),
        schedule: [S('04:40', L('Taxi na lotnisko', 'Taxi to airport', 'Taxi al aeropuerto'), L('Na lotnisku około 05:15; sprawdzić, czy bagaż leci do CUZ.', 'Reach the airport around 05:15 and confirm baggage is tagged to CUZ.', 'Llegar sobre 05:15 y confirmar equipaje hasta CUZ.')), S('07:20–12:50', L('Iquitos → Lima → Cusco', 'Iquitos → Lima → Cusco', 'Iquitos → Lima → Cusco'), L('Podczas przesiadki jeść lekko i pić wodę.', 'Eat lightly and hydrate during the connection.', 'Comer ligero e hidratarse durante la conexión.')), S('po 13:00', L('Hotel i aklimatyzacja', 'Hotel and acclimatisation', 'Hotel y aclimatación'), L('Taxi, lekki posiłek, odpoczynek. Bez alkoholu i stromych spacerów.', 'Taxi, light meal and rest. No alcohol or steep walks.', 'Taxi, comida ligera y descanso. Sin alcohol ni cuestas fuertes.'))],
        historyTitle: L('Cusco: stolica Tawantinsuyu', 'Cusco: capital of Tawantinsuyu', 'Cusco: capital del Tawantinsuyu'),
        history: [L('Cusco zostało przekształcone w XV wieku za panowania Pachacuteca w centrum administracyjne i ceremonialne państwa Inków. Z miasta wychodziły drogi organizujące ogromne Tawantinsuyu.', 'In the fifteenth century, under Pachacuti, Cusco was transformed into the administrative and ceremonial centre of the Inca state. Roads radiated from it across Tawantinsuyu.', 'En el siglo XV, bajo Pachacútec, Cusco fue transformado en centro administrativo y ceremonial del Estado inca. Desde allí partían caminos por el Tawantinsuyu.'), L('Po podboju Hiszpanie nie zburzyli całego układu. Wykorzystali inkaskie fundamenty i przestrzenie, budując kościoły oraz pałace na wcześniejszej strukturze. Miasto jest więc warstwowym dokumentem obu porządków.', 'After the conquest, the Spanish reused rather than erased the whole layout, building churches and palaces on Inca foundations. The city is a layered document of both systems.', 'Tras la conquista, los españoles reutilizaron gran parte del trazado y construyeron iglesias y palacios sobre bases incas. La ciudad es un documento de ambos sistemas.')],
        practical: [L('Objawy wysokości obserwować bez paniki, ale nie ignorować ich pogorszenia.', 'Monitor altitude symptoms without panic, but do not ignore worsening signs.', 'Observar síntomas de altura sin pánico, pero no ignorar si empeoran.'), L('Pierwszego dnia nie planować Sacsayhuamánu ani San Blas pod górę.', 'Do not plan Sacsayhuamán or a steep San Blas walk on the first day.', 'No planear Sacsayhuamán ni subir San Blas el primer día.'), L('Pić regularnie, jeść lekko i spać wcześnie.', 'Drink regularly, eat lightly and sleep early.', 'Beber con regularidad, comer ligero y dormir temprano.')],
        chapter: 'cusco', media: { category:'Cusco', target:'plaza' }
      },
      '15.09': {
        kicker: L('Czytanie miasta warstwami', 'Reading the city in layers', 'Leer la ciudad por capas'),
        lead: L('Pierwszy spokojny spacer po Cusco. Zamiast odhaczać atrakcje, patrzycie na inkaskie mury, kolonialne nadbudowy i współczesne życie centrum.', 'The first gentle Cusco walk. Rather than ticking boxes, read Inca walls, colonial additions and present-day life.', 'Primer paseo tranquilo por Cusco. En vez de marcar atracciones, leer muros incas, añadidos coloniales y vida actual.'),
        schedule: [S('rano', L('Plaza de Armas', 'Plaza de Armas', 'Plaza de Armas'), L('Powolny start, katedra z zewnątrz i orientacja w centrum.', 'Slow start, view the cathedral exterior and orient yourselves.', 'Inicio lento, exterior de la catedral y orientación.')), S('południe', L('Mercado San Pedro', 'San Pedro Market', 'Mercado San Pedro'), L('Owoce, prosty posiłek i obserwacja codziennego rytmu.', 'Fruit, a simple meal and the city’s everyday rhythm.', 'Fruta, comida sencilla y ritmo cotidiano.')), S('popołudnie', L('San Blas tylko przy energii', 'San Blas only if energy allows', 'San Blas solo con energía'), L('Taxi w górę i zejście pieszo jest rozsądniejsze niż forsowne podejście.', 'Taking a taxi up and walking down is wiser than forcing the climb.', 'Subir en taxi y bajar andando es mejor que forzar la subida.'))],
        historyTitle: L('Inkaskie fundamenty pod kolonialnym miastem', 'Inca foundations beneath the colonial city', 'Cimientos incas bajo la ciudad colonial'),
        history: [L('Plaza de Armas zajmuje część dawnego centralnego obszaru Huacaypata, znacznie większej ceremonialnej przestrzeni inkaskiego Cusco. Hiszpańskie miasto zmniejszyło i przekształciło ten układ.', 'Plaza de Armas occupies part of the former Huacaypata, a much larger ceremonial space in Inca Cusco. The Spanish city reduced and transformed it.', 'La Plaza de Armas ocupa parte del antiguo Huacaypata, espacio ceremonial mucho mayor del Cusco inca. La ciudad española lo redujo y transformó.'), L('Kolonialne kościoły i rezydencje często stoją na murach oraz działkach związanych z inkaskimi pałacami. Trzęsienia ziemi wielokrotnie niszczyły późniejsze konstrukcje, podczas gdy dobrze dopasowane mury inkaskie przetrwały.', 'Colonial churches and residences often stand on plots and walls associated with Inca palaces. Earthquakes repeatedly damaged later construction while finely fitted Inca masonry endured.', 'Iglesias y casas coloniales se levantan muchas veces sobre muros y solares incas. Los terremotos dañaron construcciones posteriores mientras la cantería inca resistió.')],
        practical: [L('Robić częste przerwy nawet wtedy, gdy samopoczucie jest dobre.', 'Take frequent breaks even when feeling well.', 'Hacer pausas frecuentes incluso sintiéndose bien.'), L('Na targu uważać na surowe soki z niepewnej wody.', 'Be cautious with raw juices made with uncertain water.', 'Cuidado con zumos preparados con agua dudosa.'), L('Nie próbować zmieścić całego Cusco w jeden dzień.', 'Do not try to fit all of Cusco into one day.', 'No intentar meter todo Cusco en un día.')],
        chapter: 'cusco', media: { category:'Cusco', target:'plaza' }
      },
      '16.09': {
        kicker: L('Drugi dzień aklimatyzacji', 'Second acclimatisation day', 'Segundo día de aclimatación'),
        lead: L('Program zależy od samopoczucia. Przy dobrej adaptacji można dodać Qorikanchę lub Sacsayhuamán; przy słabszej zostajecie w centrum.', 'The programme depends on how you feel. With good adaptation add Qorikancha or Sacsayhuamán; otherwise stay in the centre.', 'El programa depende de cómo os encontréis. Con buena adaptación, añadir Qorikancha o Sacsayhuamán; si no, quedarse en el centro.'),
        schedule: [S('rano', L('Qorikancha', 'Qorikancha', 'Qorikancha'), L('Najlepsze miejsce, aby porównać inkaską kamieniarkę z kolonialną nadbudową.', 'The best place to compare Inca masonry with colonial construction above it.', 'El mejor lugar para comparar cantería inca con construcción colonial.')), S('południe', L('Odpoczynek', 'Rest', 'Descanso'), L('Długi lunch i ocena wysokości przed decyzją o dalszym programie.', 'Long lunch and an altitude check before deciding what comes next.', 'Almuerzo largo y evaluación de la altura antes de seguir.')), S('popołudnie', L('Sacsayhuamán opcjonalnie', 'Optional Sacsayhuamán', 'Sacsayhuamán opcional'), L('Najlepiej taxi w górę; zejście pieszo, jeżeli wszyscy czują się stabilnie.', 'Prefer a taxi uphill; walk down only if everyone feels stable.', 'Mejor taxi para subir; bajar andando solo si todos están estables.'))],
        historyTitle: L('Qorikancha i Sacsayhuamán: religia oraz władza', 'Qorikancha and Sacsayhuamán: religion and power', 'Qorikancha y Sacsayhuamán: religión y poder'),
        history: [L('Qorikancha była jednym z najważniejszych sanktuariów państwa Inków, związanym z kultem Słońca i rytuałami imperialnymi. Po podboju na jej murach powstał klasztor Santo Domingo.', 'Qorikancha was one of the Inca state’s most important sanctuaries, associated with the Sun and imperial ritual. The convent of Santo Domingo was built over its walls after the conquest.', 'Qorikancha fue uno de los santuarios más importantes del Estado inca, asociado al Sol y al ritual imperial. Tras la conquista se construyó encima el convento de Santo Domingo.'), L('Sacsayhuamán jest monumentalnym kompleksem nad Cusco, którego funkcja wykraczała poza prostą fortecę. Jego place, mury i położenie wskazują również na znaczenie ceremonialne oraz polityczne.', 'Sacsayhuamán is a monumental complex above Cusco whose function went beyond a simple fortress. Its plazas, walls and setting also indicate ceremonial and political importance.', 'Sacsayhuamán es un complejo monumental sobre Cusco cuya función superaba una simple fortaleza. Sus plazas, muros y ubicación indican también importancia ceremonial y política.')],
        practical: [L('Nie łączyć Sacsayhuamánu z długim marszem po stromym San Blas.', 'Do not combine Sacsayhuamán with a long steep San Blas walk.', 'No combinar Sacsayhuamán con una larga subida por San Blas.'), L('Przy narastającym bólu głowy wrócić do hotelu i odpocząć.', 'Return to the hotel and rest if the headache worsens.', 'Volver al hotel y descansar si aumenta el dolor de cabeza.'), L('Wieczorem przygotować rzeczy do całodniowego przejazdu 17.09.', 'Prepare for the full-day transfer on 17 September.', 'Preparar por la noche el traslado de todo el día del 17.')],
        chapter: 'cusco', media: { category:'Cusco', target:'qorikancha' }
      },
      '17.09': {
        kicker: L('Święta Dolina jako korytarz imperium', 'The Sacred Valley as an imperial corridor', 'El Valle Sagrado como corredor imperial'),
        lead: L('To nie jest zwykły transfer. Przejazd łączy miejsca pokazujące rolnictwo, administrację, sól, tekstylia i kontrolę strategicznej doliny Urubamby.', 'This is not a simple transfer. The route connects agriculture, administration, salt, textiles and control of the Urubamba valley.', 'No es un simple traslado. La ruta conecta agricultura, administración, sal, textiles y control del valle del Urubamba.'),
        schedule: [S('rano', L('Pisac', 'Pisac', 'Pisac'), L('Ruiny przed targiem. Tarasy, góra i kontrola wejścia do doliny.', 'Ruins before the market: terraces, mountain setting and control of the valley entrance.', 'Ruinas antes del mercado: terrazas, montaña y control de la entrada al valle.')), S('środek dnia', L('Moray i Maras', 'Moray and Maras', 'Moray y Maras'), L('Koncentryczne tarasy oraz krajobraz produkcji soli.', 'Concentric terraces and a landscape of salt production.', 'Terrazas concéntricas y paisaje de producción de sal.')), S('popołudnie', L('Chinchero → Ollantaytambo', 'Chinchero → Ollantaytambo', 'Chinchero → Ollantaytambo'), L('Przy opóźnieniu skracać postoje, a nie jechać nerwowo po zmroku.', 'If delayed, shorten stops rather than drive nervously after dark.', 'Si hay retraso, acortar paradas en vez de conducir con prisa de noche.'))],
        historyTitle: L('Dlaczego dolina była tak ważna', 'Why the valley mattered', 'Por qué el valle era tan importante'),
        history: [L('Dolina Urubamby leży niżej i ma łagodniejszy klimat niż Cusco, dlatego była ważnym zapleczem rolniczym, zwłaszcza dla kukurydzy. Sieć tarasów, dróg i osiedli łączyła produkcję z administracją państwa.', 'The Urubamba valley lies lower and has a milder climate than Cusco, making it an important agricultural zone, especially for maize. Terraces, roads and settlements connected production to state administration.', 'El valle del Urubamba está más bajo y tiene clima más suave que Cusco, por lo que fue importante para la agricultura, especialmente el maíz. Terrazas, caminos y asentamientos conectaban producción y administración.'), L('Pisac i Ollantaytambo kontrolowały strategiczne odcinki doliny. Moray, Maras i Chinchero pokazują inne sposoby organizacji krajobrazu: eksperymentowanie z mikroklimatami, eksploatację soli i wysokogórskie osadnictwo.', 'Pisac and Ollantaytambo controlled strategic parts of the valley. Moray, Maras and Chinchero reveal other ways of organising landscape: microclimates, salt extraction and highland settlement.', 'Pisac y Ollantaytambo controlaban zonas estratégicas. Moray, Maras y Chinchero muestran otras formas de organizar el paisaje: microclimas, extracción de sal y asentamiento de altura.')],
        practical: [L('Potwierdzić z TaxiDatum realny czas całej pętli przed startem.', 'Confirm the realistic total duration with TaxiDatum before departure.', 'Confirmar con TaxiDatum la duración real antes de salir.'), L('Mieć gotówkę na wejścia i drobne zakupy.', 'Carry cash for admissions and small purchases.', 'Llevar efectivo para entradas y compras pequeñas.'), L('Nie dopuścić, by targ w Pisac zjadł czas potrzebny na ruiny.', 'Do not let Pisac market consume the time needed for the ruins.', 'No dejar que el mercado de Pisac quite el tiempo de las ruinas.')],
        chapter: 'sacred', media: { category:'Sacred Valley', target:'pisac' }
      },
      '18.09': {
        kicker: L('Żywe miasto Inków', 'A living Inca town', 'Un pueblo inca vivo'),
        lead: L('Cały dzień bez przejazdu. Ruiny rano, stare uliczki i kanały później. Tempo ma być spokojne przed Machu Picchu.', 'A full day without travel. Ruins in the morning, old streets and canals later. Keep the pace calm before Machu Picchu.', 'Día completo sin traslado. Ruinas por la mañana, calles y canales después. Ritmo tranquilo antes de Machu Picchu.'),
        schedule: [S('rano', L('Kompleks archeologiczny', 'Archaeological complex', 'Complejo arqueológico'), L('Tarasy, sektor świątynny i widok na dolinę przed większym tłokiem.', 'Terraces, temple sector and valley views before larger crowds.', 'Terrazas, sector de templos y vistas antes de más gente.')), S('południe', L('Rynek i przerwa', 'Square and rest', 'Plaza y descanso'), L('Długi lunch, bez dokładania kolejnego podjazdu.', 'Long lunch without adding another excursion.', 'Almuerzo largo sin añadir otra excursión.')), S('popołudnie', L('Stare miasto i kanały', 'Old town and canals', 'Casco antiguo y canales'), L('Zwracać uwagę na układ kancha, wodę i ciągłość użytkowania.', 'Notice the kancha layout, water and continuity of use.', 'Observar el trazado kancha, el agua y la continuidad de uso.'))],
        historyTitle: L('Ollantaytambo: rezydencja, świątynia i punkt oporu', 'Ollantaytambo: estate, temple and resistance', 'Ollantaytambo: hacienda, templo y resistencia'),
        history: [L('Ollantaytambo zostało monumentalnie przebudowane za Pachacuteca jako królewska posiadłość i ważny punkt doliny. Ogromne tarasy oraz niedokończony sektor świątynny pokazują skalę przedsięwzięcia.', 'Ollantaytambo was monumentally rebuilt under Pachacuti as a royal estate and key valley site. Its huge terraces and unfinished temple sector reveal the scale of the project.', 'Ollantaytambo fue reconstruido monumentalmente bajo Pachacútec como propiedad real y punto clave del valle. Sus enormes terrazas y sector templario inacabado muestran la escala del proyecto.'), L('Po zdobyciu Cusco Manco Inca wykorzystał Ollantaytambo jako bazę oporu. W 1537 roku siły inkaskie odparły tu Hiszpanów, wykorzystując tarasy, wysokość i zalanie pól, choć później wycofały się w stronę Vilcabamby.', 'After Cusco fell, Manco Inca used Ollantaytambo as a resistance base. In 1537 Inca forces repelled a Spanish attack using terraces, height and flooded fields, though they later withdrew toward Vilcabamba.', 'Tras la caída de Cusco, Manco Inca usó Ollantaytambo como base de resistencia. En 1537 las fuerzas incas rechazaron un ataque español usando terrazas, altura y campos inundados, aunque después se retiraron hacia Vilcabamba.')],
        practical: [L('Wejść do ruin możliwie wcześnie.', 'Enter the ruins as early as practical.', 'Entrar en las ruinas lo antes posible.'), L('Pinkuylluna traktować jako opcję tylko przy dobrych nogach i pogodzie.', 'Treat Pinkuylluna as optional only with good legs and weather.', 'Considerar Pinkuylluna solo con buenas piernas y tiempo.'), L('Wieczorem potwierdzić przechowanie dużych plecaków.', 'Confirm storage of the large backpacks in the evening.', 'Confirmar por la noche el depósito de mochilas grandes.')],
        chapter: 'olla', media: { category:'Ollantaytambo', target:'sun-temple' }
      },
      '19.09': {
        kicker: L('Pociąg do Aguas i operacja Ruta 2', 'Train to Aguas and Route 2 operation', 'Tren a Aguas y operación Ruta 2'),
        lead: L('Dzień pozornie lekki, ale kluczowy. Duże plecaki zostają w Ollantaytambo, a po przyjeździe priorytetem jest procedura zakupu dodatkowego wejścia.', 'A seemingly light but crucial day. Large backpacks stay in Ollantaytambo; after arrival the priority is the extra-entry purchase procedure.', 'Día aparentemente ligero pero clave. Las mochilas grandes quedan en Ollantaytambo; al llegar, la prioridad es comprar la entrada adicional.'),
        schedule: [S('przed 12:25', L('Stacja Ollantaytambo', 'Ollantaytambo station', 'Estación Ollantaytambo'), L('Bilety offline, małe plecaki i brak pośpiechu.', 'Offline tickets, small backpacks and no rush.', 'Billetes sin conexión, mochilas pequeñas y sin prisas.')), S('12:55–około 14:25', L('Pociąg do Aguas Calientes', 'Train to Aguas Calientes', 'Tren a Aguas Calientes'), L('Trasa wzdłuż Urubamby pokazuje szybkie zejście w wilgotniejszy krajobraz.', 'The Urubamba route reveals a rapid descent into a wetter landscape.', 'La ruta junto al Urubamba muestra un rápido descenso hacia un paisaje más húmedo.')), S('po przyjeździe', L('Centro Cultural', 'Cultural Centre', 'Centro Cultural'), L('Zostawić małe plecaki i iść z paszportami. Priorytet: 2-A 13:00, potem 2-B 13:00.', 'Leave small bags and go with passports. Priority: 2-A at 13:00, then 2-B at 13:00.', 'Dejar mochilas pequeñas e ir con pasaportes. Prioridad: 2-A 13:00, luego 2-B 13:00.'))],
        historyTitle: L('Od kolejowej osady do Machupicchu Pueblo', 'From railway settlement to Machupicchu Pueblo', 'De asentamiento ferroviario a Machupicchu Pueblo'),
        history: [L('Aguas Calientes rozwinęło się w XX wieku wokół kolei i obsługi stanowiska archeologicznego. Jego położenie w ciasnej dolinie sprawia, że miasto jest funkcjonalnym zapleczem, a nie historycznym odpowiednikiem Ollantaytambo.', 'Aguas Calientes developed in the twentieth century around the railway and the archaeological site. In its narrow valley it functions as a service base, not a historic counterpart to Ollantaytambo.', 'Aguas Calientes se desarrolló en el siglo XX alrededor del ferrocarril y del sitio arqueológico. En su valle estrecho funciona como base de servicios, no como equivalente histórico de Ollantaytambo.'), L('Kolej zmieniła dostęp do regionu i umożliwiła rozwój masowej turystyki. Dzisiejsza logistyka autobusów, pociągów i limitowanych tras jest skutkiem ochrony bardzo kruchego miejsca przy ogromnym popycie.', 'The railway transformed access and enabled mass tourism. Today’s buses, trains and limited circuits reflect the challenge of protecting a fragile site under enormous demand.', 'El ferrocarril transformó el acceso y permitió el turismo masivo. Los buses, trenes y circuitos limitados responden al reto de proteger un lugar frágil con enorme demanda.')],
        practical: [L('Nie nosić dużych plecaków do Aguas.', 'Do not take large backpacks to Aguas.', 'No llevar mochilas grandes a Aguas.'), L('Paszporty i gotówka muszą być natychmiast dostępne.', 'Passports and cash must be immediately accessible.', 'Pasaportes y efectivo deben estar accesibles.'), L('Wieczorem przygotować ubrania, wodę i bilety na pobudkę około 05:00.', 'Prepare clothing, water and tickets for the 05:00 wake-up.', 'Preparar ropa, agua y billetes para despertar sobre las 05:00.')],
        chapter: 'machu', media: { category:'Machu Picchu', target:'overview' }, route: 'machu'
      },
      '20.09': {
        kicker: L('Najważniejszy dzień wyprawy', 'The expedition’s key day', 'El día clave de la expedición'),
        lead: L('Ruta 3-A o 07:00, wejście na Waynapicchu i — jeżeli uda się kupić — druga Ruta 2 po południu. Dzień musi być prowadzony według marginesów, nie emocji.', 'Route 3-A at 07:00, the Waynapicchu climb and, if secured, a second Route 2 in the afternoon. Run the day by margins, not emotion.', 'Ruta 3-A a las 07:00, subida a Waynapicchu y, si se consigue, segunda Ruta 2 por la tarde. Gestionar por márgenes, no por emoción.'),
        schedule: [S('05:00–06:40', L('Pobudka, autobus i kontrola', 'Wake-up, bus and control', 'Despertar, bus y control'), L('Pełne śniadanie, paszporty, mały plecak i kolejka z marginesem.', 'Full breakfast, passports, small bag and queue with margin.', 'Desayuno completo, pasaportes, mochila pequeña y cola con margen.')), S('07:00–około 11:30', L('Ruta 3-A + Waynapicchu', 'Route 3-A + Waynapicchu', 'Ruta 3-A + Waynapicchu'), L('Spokojne tempo, telefon schowany na stromych schodach i tracker etapów.', 'Calm pace, phone away on steep stairs and use the route tracker.', 'Ritmo tranquilo, teléfono guardado en escaleras y tracker de etapas.')), S('13:00 lub 14:00', L('Opcjonalna Ruta 2', 'Optional Route 2', 'Ruta 2 opcional'), L('Jeżeli bilet jest kupiony i grupa ma siłę. Potem autobus, bagaże i pociąg z bezpiecznym marginesem.', 'Only if the ticket is secured and the group has energy. Then bus, luggage and train with safe margin.', 'Solo con billete y energía. Después bus, equipaje y tren con margen seguro.'))],
        historyTitle: L('Machu Picchu: pewniki, hipotezy i odkrywanie', 'Machu Picchu: evidence, hypotheses and discovery', 'Machu Picchu: evidencias, hipótesis y descubrimiento'),
        history: [L('Machu Picchu powstało w XV wieku w okresie ekspansji państwa Inków. Wielu badaczy wiąże je z Pachacutecem i funkcją królewskiej posiadłości, lecz stanowisko pełniło również role ceremonialne, administracyjne oraz produkcyjne. Nie istnieje jedna pewna etykieta wyjaśniająca cały kompleks.', 'Machu Picchu was built in the fifteenth century during Inca expansion. Many scholars associate it with Pachacuti and a royal estate, but it also served ceremonial, administrative and productive roles. No single label explains the whole complex.', 'Machu Picchu fue construido en el siglo XV durante la expansión inca. Muchos investigadores lo vinculan con Pachacútec y una propiedad real, pero también tuvo funciones ceremoniales, administrativas y productivas. Una sola etiqueta no explica todo el conjunto.'), L('Miejsce nie było „zagubione” dla mieszkańców regionu. Hiram Bingham dotarł tu w 1911 roku dzięki lokalnym informatorom i nagłośnił stanowisko międzynarodowo. Późniejsze wykopaliska, konserwacja i turystyka zmieniły sposób jego postrzegania.', 'The site was not “lost” to local residents. Hiram Bingham reached it in 1911 with local guidance and publicised it internationally. Later excavation, conservation and tourism transformed how it is understood.', 'El sitio no estaba “perdido” para la población local. Hiram Bingham llegó en 1911 con guía local y lo difundió internacionalmente. Excavación, conservación y turismo transformaron después su interpretación.'), L('Najważniejszym osiągnięciem jest integracja architektury z grzbietem górskim: tarasy stabilizują zbocze, system wody zasila kolejne sektory, a naturalne skały są częścią kompozycji zamiast przeszkodą do usunięcia.', 'Its central achievement is integration with the mountain ridge: terraces stabilise slopes, water serves successive sectors and natural rock becomes part of the design rather than an obstacle.', 'Su logro central es la integración con la montaña: las terrazas estabilizan pendientes, el agua alimenta sectores y la roca natural forma parte del diseño.')],
        practical: [L('Na miejscu używać osobnego modułu Machu, a nie tej strony dnia.', 'Use the dedicated Machu module on site, not this day page.', 'En el sitio usar el módulo Machu, no esta página del día.'), L('Nie ryzykować pociągu 18:20 przy drugim wejściu.', 'Do not risk the 18:20 train with a second entry.', 'No arriesgar el tren de 18:20 con segunda entrada.'), L('Przy deszczu lub mokrych schodach bezpieczeństwo wygrywa z kadrem.', 'In rain or on wet stairs, safety beats the photograph.', 'Con lluvia o escaleras mojadas, la seguridad gana a la foto.')],
        chapter: 'machu', media: { category:'Machu Picchu', target:'summit' }, route: 'machu'
      },
      '21.09': {
        kicker: L('Dzień transferowy', 'Transfer day', 'Día de traslado'),
        lead: L('Po Machu Picchu nie dokładacie zwiedzania. Celem jest bezpieczny transfer z Ollantaytambo lub Cusco na lotnisko i spokojny lot do Limy.', 'No sightseeing after Machu Picchu. The goal is a safe transfer from Ollantaytambo or Cusco to the airport and a calm flight to Lima.', 'Sin turismo después de Machu Picchu. Objetivo: traslado seguro desde Ollantaytambo o Cusco al aeropuerto y vuelo tranquilo a Lima.'),
        schedule: [S('rano', L('Regeneracja i bagaż', 'Recovery and luggage', 'Recuperación y equipaje'), L('Śniadanie, kontrola rzeczy i odbiór dużych plecaków.', 'Breakfast, gear check and collect large backpacks.', 'Desayuno, revisión y recoger mochilas grandes.')), S('przed lotem', L('Taxi na lotnisko', 'Taxi to airport', 'Taxi al aeropuerto'), L('Przy starcie z Ollantaytambo wybierać lot po południu.', 'When starting in Ollantaytambo, choose an afternoon flight.', 'Saliendo de Ollantaytambo, elegir vuelo de tarde.')), S('wieczór', L('Lima', 'Lima', 'Lima'), L('Check-in i jedzenie blisko noclegu. Bez ambitnego wieczoru.', 'Check in and eat near the accommodation. No ambitious evening.', 'Check-in y comida cerca. Sin noche ambiciosa.'))],
        historyTitle: L('Drogi Inków i współczesne korytarze podróży', 'Inca roads and modern travel corridors', 'Caminos incas y corredores modernos'),
        history: [L('Inkaskie państwo łączyło regiony rozbudowaną siecią Qhapaq Ñan, przystosowaną do ruchu pieszych, karawan lam i posłańców. Dzisiejszy przejazd samochodem i lot pokazuje zupełnie inną skalę czasu, ale nadal korzysta z tych samych naturalnych korytarzy dolin.', 'The Inca state connected regions through Qhapaq Ñan for pedestrians, llama caravans and messengers. Modern road and air travel compress time, yet still follow the natural corridors of valleys.', 'El Estado inca conectaba regiones con el Qhapaq Ñan para peatones, llamas y mensajeros. Carretera y avión comprimen el tiempo, pero siguen corredores naturales de los valles.'), L('Cusco i Lima reprezentują dwa odmienne centra w historii Peru: andyjską stolicę imperium oraz kolonialno-republikańską stolicę wybrzeża. Przelot między nimi w kilka godzin zamyka najważniejszy kontrast całej podróży.', 'Cusco and Lima represent two different historical centres: the Andean imperial capital and the coastal colonial-republican capital. Flying between them closes the trip’s central contrast.', 'Cusco y Lima representan dos centros históricos distintos: capital imperial andina y capital colonial-republicana costera. El vuelo resume el gran contraste del viaje.')],
        practical: [L('Nie kupować lotu zbyt wcześnie rano przy noclegu w Ollantaytambo.', 'Do not book an early morning flight when sleeping in Ollantaytambo.', 'No reservar vuelo temprano durmiendo en Ollantaytambo.'), L('Zachować duży margines na ruch i roboty drogowe.', 'Keep a large margin for traffic and roadworks.', 'Dejar margen amplio por tráfico y obras.'), L('Po przylocie do Limy tylko prosta kolacja i sen.', 'After landing in Lima, have a simple dinner and sleep.', 'Tras llegar a Lima, cena sencilla y dormir.')],
        chapter: 'sacred', media: { category:'Sacred Valley', target:'chinchero' }
      },
      '22.09': {
        kicker: L('Pełny reset w Limie', 'Full reset in Lima', 'Descanso completo en Lima'),
        lead: L('Po Amazonii, wysokości i Machu Picchu ten dzień pozostaje świadomie pusty. To bufor chroniący resztę wyjazdu przed skumulowanym zmęczeniem.', 'After Amazonia, altitude and Machu Picchu, this day stays deliberately empty. It protects the rest of the trip from accumulated fatigue.', 'Después de Amazonía, altura y Machu Picchu, este día queda deliberadamente vacío para evitar fatiga acumulada.'),
        schedule: [S('rano', L('Sen bez budzika', 'Sleep without alarm', 'Dormir sin alarma'), L('Nie planować śniadania wymagającego rezerwacji.', 'Do not plan a breakfast requiring a reservation.', 'No planear desayuno con reserva.')), S('dzień', L('Pranie i porządek', 'Laundry and organisation', 'Lavandería y orden'), L('Backup zdjęć, kontrola wydatków i odpoczynek.', 'Back up photos, review expenses and rest.', 'Copia de fotos, revisar gastos y descansar.')), S('wieczór', L('Krótki spacer', 'Short walk', 'Paseo corto'), L('Malecón albo kolacja blisko noclegu, zależnie od energii.', 'Malecón or dinner nearby, depending on energy.', 'Malecón o cena cerca, según energía.'))],
        historyTitle: L('Lima jako miasto trzęsień ziemi i odbudowy', 'Lima as a city of earthquakes and rebuilding', 'Lima como ciudad de terremotos y reconstrucción'),
        history: [L('Lima wielokrotnie doświadczała silnych trzęsień ziemi, które niszczyły kościoły, domy i infrastrukturę. Kolejne odbudowy zmieniały styl miasta oraz technologie budowlane.', 'Lima has repeatedly experienced major earthquakes that destroyed churches, houses and infrastructure. Each rebuilding changed the city’s style and construction methods.', 'Lima sufrió repetidos terremotos que destruyeron iglesias, casas e infraestructura. Cada reconstrucción cambió estilo y técnicas constructivas.'), L('Współczesna metropolia rozrosła się gwałtownie w XX wieku dzięki migracji z Andów i innych regionów. Dzisiejsza Lima jest więc nie tylko kolonialnym centrum, lecz złożonym miastem migracji, nierówności i nowych kultur miejskich.', 'The metropolis expanded rapidly in the twentieth century through migration from the Andes and elsewhere. Modern Lima is not merely colonial; it is a city of migration, inequality and new urban cultures.', 'La metrópoli creció rápidamente en el siglo XX por migración desde los Andes y otras regiones. Lima moderna no es solo colonial: es ciudad de migración, desigualdad y nuevas culturas urbanas.')],
        practical: [L('Nie zamieniać dnia odpoczynku w „stracony dzień”.', 'Do not treat a rest day as a lost day.', 'No considerar el descanso como día perdido.'), L('Wykonać pełny backup aplikacji i obserwacji.', 'Make a full app and sightings backup.', 'Hacer copia completa de la app y observaciones.'), L('Sprawdzić godziny wylotów 25–26.09.', 'Check departure times for 25–26 September.', 'Revisar vuelos del 25–26 de septiembre.')],
        chapter: 'lima', media: { category:'Lima', target:'malecon' }
      },
      '23.09': {
        kicker: L('Miraflores albo Barranco', 'Miraflores or Barranco', 'Miraflores o Barranco'),
        lead: L('Lekki dzień miejski. Wybieracie jedną dzielnicę jako główny temat, zamiast przemieszczać się bez końca po całej Limie.', 'A light urban day. Choose one district as the main theme instead of crossing all of Lima repeatedly.', 'Día urbano ligero. Elegir un distrito como tema principal en vez de cruzar Lima sin parar.'),
        schedule: [S('rano', L('Malecón / Huaca Pucllana', 'Malecón / Huaca Pucllana', 'Malecón / Huaca Pucllana'), L('Spacer po klifach albo prekolumbijska warstwa Miraflores.', 'Clifftop walk or Miraflores’ pre-Columbian layer.', 'Paseo por acantilados o capa precolombina de Miraflores.')), S('popołudnie', L('Barranco', 'Barranco', 'Barranco'), L('Puente de los Suspiros, uliczki i kawa bez gonienia galerii.', 'Bridge of Sighs, streets and coffee without rushing galleries.', 'Puente de los Suspiros, calles y café sin correr por galerías.')), S('wieczór', L('Kolacja', 'Dinner', 'Cena'), L('Jedno dobre miejsce, rezerwacja tylko jeżeli naprawdę potrzebna.', 'One good place; reserve only if genuinely needed.', 'Un buen lugar; reservar solo si hace falta.'))],
        historyTitle: L('Od kurortu do dzielnicy artystycznej', 'From resort to arts district', 'De balneario a barrio artístico'),
        history: [L('Miraflores rozwinęło się jako podmiejska i nadmorska dzielnica elit, a później jako nowoczesne centrum mieszkaniowe i handlowe. Wojna o Pacyfik pozostawiła tu ślady walk z 1881 roku.', 'Miraflores grew as a suburban coastal district and later a modern residential and commercial centre. The War of the Pacific left the memory of fighting here in 1881.', 'Miraflores creció como distrito costero suburbano y después centro moderno residencial y comercial. La Guerra del Pacífico dejó memoria de combates en 1881.'), L('Barranco rozwijało się jako nadmorski kurort, a w XX wieku zyskało reputację dzielnicy artystów, pisarzy i muzyków. Dzisiejsza popularność łączy historyczną zabudowę z restauracjami oraz nocnym życiem.', 'Barranco developed as a seaside resort and gained a twentieth-century reputation for artists, writers and musicians. Today historic buildings mix with restaurants and nightlife.', 'Barranco se desarrolló como balneario y en el siglo XX ganó fama entre artistas, escritores y músicos. Hoy mezcla edificios históricos con restaurantes y vida nocturna.')],
        practical: [L('Nie łączyć Centro Histórico i Barranco w jeden krótki dzień.', 'Do not combine the Historic Centre and Barranco in one short day.', 'No combinar Centro Histórico y Barranco en un día corto.'), L('W godzinach szczytu zakładać duże opóźnienia przejazdu.', 'Assume major traffic delays at peak times.', 'Prever grandes retrasos en hora punta.'), L('Przy klifach wiatr może być chłodniejszy niż w głębi miasta.', 'Clifftops can be cooler and windier than inland streets.', 'Los acantilados pueden ser más fríos y ventosos.')],
        chapter: 'lima', media: { category:'Lima', target:'barranco' }
      },
      '24.09': {
        kicker: L('Ostatni wspólny pełny dzień', 'Last full day together', 'Último día completo juntos'),
        lead: L('Dzień należy do grupy. Możecie wybrać centrum historyczne, jedzenie albo całkowity luz — ale nie próbować zamknąć wszystkich braków naraz.', 'The day belongs to the group. Choose the historic centre, food or complete relaxation, but do not chase every remaining item.', 'El día pertenece al grupo. Elegir centro histórico, comida o descanso total, sin perseguir todo lo pendiente.'),
        schedule: [S('rano', L('Wspólna decyzja', 'Group decision', 'Decisión del grupo'), L('Jedna główna aktywność uzgodniona przy śniadaniu.', 'Agree on one main activity at breakfast.', 'Acordar una actividad principal en el desayuno.')), S('dzień', L('Centrum lub jedzenie', 'Historic centre or food', 'Centro o gastronomía'), L('Plaza Mayor i kolonialna historia albo spokojny dzień kulinarny.', 'Plaza Mayor and colonial history, or a calm food-focused day.', 'Plaza Mayor e historia colonial, o día gastronómico tranquilo.')), S('wieczór', L('Ostatnia wspólna kolacja', 'Final dinner together', 'Última cena juntos'), L('Backup wspólnych zdjęć i ustalenie transportu na lotnisko.', 'Back up shared photographs and confirm airport transport.', 'Copiar fotos compartidas y confirmar transporte al aeropuerto.'))],
        historyTitle: L('Kolonialne centrum i republikańska stolica', 'Colonial centre and republican capital', 'Centro colonial y capital republicana'),
        history: [L('Historyczne centrum Limy było siedzibą władzy Wicekrólestwa Peru, jednego z najważniejszych ośrodków hiszpańskiej Ameryki Południowej. Wokół głównego placu skupiono katedrę, pałace i administrację.', 'Lima’s historic centre was the seat of the Viceroyalty of Peru, one of Spanish South America’s most important centres. Cathedral, palaces and administration surrounded the main square.', 'El centro histórico fue sede del Virreinato del Perú, uno de los centros más importantes de Sudamérica española. Catedral, palacios y administración rodeaban la plaza principal.'), L('Po niepodległości Lima pozostała stolicą republiki. Jej monumentalne budynki przedstawiają oficjalną historię państwa, ale współczesna metropolia powstała również dzięki migracji i pracy ludzi z całego Peru.', 'After independence Lima remained the republican capital. Monumental buildings tell the state’s official story, while the modern metropolis was also built through migration and labour from all Peru.', 'Tras la independencia Lima siguió siendo capital republicana. Los edificios cuentan la historia oficial, pero la metrópoli moderna también fue construida por migración y trabajo de todo el Perú.')],
        practical: [L('Do Centro jechać i wracać poza najgorszym szczytem, o ile to możliwe.', 'Travel to and from the centre outside the worst peak traffic if possible.', 'Ir y volver del centro fuera de la peor hora punta si es posible.'), L('Telefony w centrum trzymać dyskretnie.', 'Keep phones discreet in the centre.', 'Mantener teléfonos discretos en el centro.'), L('Wieczorem każdy potwierdza dokumenty i limit bagażu.', 'Everyone confirms documents and baggage allowance in the evening.', 'Por la noche todos revisan documentos y equipaje.')],
        chapter: 'lima', media: { category:'Lima', target:'centro' }
      },
      '25.09': {
        kicker: L('Wyloty Daniela i Weroniki', 'Daniel and Weronika depart', 'Salen Daniel y Weronika'),
        lead: L('Dzień rozdzielenia grupy. Priorytety to poprawne godziny wyjazdu, margines na ruch i sprawdzenie, czy nic nie zostało w mieszkaniu.', 'The group splits today. Priorities: correct departure times, traffic margin and a final apartment sweep.', 'Hoy se separa el grupo. Prioridades: horarios correctos, margen por tráfico y revisión final del alojamiento.'),
        schedule: [S('rano', L('Pakowanie i kontrola', 'Packing and checks', 'Equipaje y revisión'), L('Paszporty, bilety, ładowarki, szafy, łazienka i kopia zdjęć.', 'Passports, tickets, chargers, wardrobes, bathroom and photo backup.', 'Pasaportes, billetes, cargadores, armarios, baño y copia de fotos.')), S('przed wylotami', L('Transfery na lotnisko', 'Airport transfers', 'Traslados al aeropuerto'), L('Nie zakładać, że przejazd zajmie tyle co nocą.', 'Do not assume daytime travel takes as little as at night.', 'No asumir que el traslado diurno tarda como de noche.')), S('po odjeździe', L('Kuba zostaje w Limie', 'Kuba remains in Lima', 'Kuba se queda en Lima'), L('Spokojny wieczór i przygotowanie własnego wylotu 26.09.', 'Quiet evening and preparation for the 26 September departure.', 'Noche tranquila y preparación de la salida del 26.'))],
        historyTitle: L('Callao: port i lotnicza brama kraju', 'Callao: port and air gateway', 'Callao: puerto y puerta aérea'),
        history: [L('Callao od epoki kolonialnej był najważniejszym portem Limy. Przepływały przez niego towary, ludzie i srebro, a jego znaczenie czyniło go celem ataków oraz fortyfikacji.', 'Since the colonial era, Callao has been Lima’s principal port. Goods, people and silver passed through it, making it both strategic and fortified.', 'Desde la colonia, Callao fue el principal puerto de Lima. Por allí pasaron mercancías, personas y plata, lo que lo hizo estratégico y fortificado.'), L('Współczesne lotnisko kontynuuje rolę Callao jako bramy międzynarodowej. Ruch wokół lotniska łączy port, przemysł, gęstą zabudowę i najważniejszy węzeł komunikacyjny Peru.', 'The modern airport continues Callao’s role as an international gateway, amid port activity, industry, dense neighbourhoods and Peru’s main transport hub.', 'El aeropuerto moderno continúa el papel del Callao como puerta internacional, entre puerto, industria, barrios densos y el principal nodo de transporte del Perú.')],
        practical: [L('Każdy transfer planować osobno według godziny lotu.', 'Plan each transfer separately according to flight time.', 'Planear cada traslado según la hora del vuelo.'), L('Po wyjeździe pierwszej osoby zrobić ponowną kontrolę mieszkania.', 'Search the apartment again after the first person leaves.', 'Revisar el alojamiento de nuevo tras salir la primera persona.'), L('Wspólne koszty rozliczyć przed rozdzieleniem grupy.', 'Settle shared costs before the group separates.', 'Liquidar gastos compartidos antes de separarse.')],
        chapter: 'lima', media: { category:'Lima', target:'malecon' }
      },
      '26.09': {
        kicker: L('Powrót Kuby', 'Kuba’s return', 'Regreso de Kuba'),
        lead: L('Ostatni dzień jest czysto operacyjny. Wczesny transfer, lotnisko i zabezpieczenie danych z wyprawy.', 'The final day is purely operational: early transfer, airport and securing the trip data.', 'El último día es puramente operativo: traslado temprano, aeropuerto y asegurar los datos del viaje.'),
        schedule: [S('wcześnie rano', L('Ostatnia kontrola', 'Final check', 'Última revisión'), L('Paszport, portfel, telefon, ładowarki, kopia aplikacji i zdjęć.', 'Passport, wallet, phone, chargers and backups of app and photos.', 'Pasaporte, cartera, teléfono, cargadores y copias de app y fotos.')), S('przed lotem', L('Transfer na lotnisko', 'Airport transfer', 'Traslado al aeropuerto'), L('Zarezerwować margines większy niż podpowiada nawigacja.', 'Leave more margin than navigation suggests.', 'Dejar más margen del que sugiere la navegación.')), S('po odprawie', L('Zamknięcie ekspedycji', 'Close the expedition', 'Cerrar la expedición'), L('Nie usuwać danych z aplikacji. Po powrocie plan zostanie przekształcony w kronikę.', 'Do not delete app data. After returning, the plan can become the expedition chronicle.', 'No borrar datos de la app. Al volver, el plan podrá convertirse en crónica.'))],
        historyTitle: L('Podróż jako zapis, nie tylko trasa', 'Travel as a record, not only a route', 'Viaje como registro, no solo ruta'),
        history: [L('Wielkie relacje z Peru przez stulecia tworzyli kronikarze, przyrodnicy, archeolodzy i podróżnicy. Każdy zapisywał kraj przez własne cele i uprzedzenia. Wasz Journal jest małym, prywatnym odpowiednikiem takiego źródła.', 'For centuries Peru has been described by chroniclers, naturalists, archaeologists and travellers, each through personal aims and biases. Your Journal is a small private version of such a source.', 'Durante siglos, cronistas, naturalistas, arqueólogos y viajeros describieron el Perú desde sus propios objetivos y prejuicios. Vuestro Journal es una pequeña fuente privada de ese tipo.'), L('Najcenniejsze będą konkretne obserwacje: godziny, pogoda, reakcje, pomyłki i zmiany planu. To one odróżnią prawdziwą historię wyprawy od katalogu atrakcji.', 'The most valuable details will be times, weather, reactions, mistakes and plan changes. They distinguish the real expedition story from an attraction catalogue.', 'Lo más valioso serán horas, clima, reacciones, errores y cambios de plan. Eso distingue la historia real de un catálogo de atracciones.')],
        practical: [L('Eksportować pełny backup przed wyjazdem na lotnisko.', 'Export a full backup before leaving for the airport.', 'Exportar copia completa antes de salir al aeropuerto.'), L('Nie czyścić pamięci podręcznej aplikacji podczas podróży powrotnej.', 'Do not clear the app cache during the return journey.', 'No borrar la caché de la app durante el regreso.'), L('Po powrocie skopiować ZIP projektu i backup w dwa miejsca.', 'After returning, copy the project ZIP and backup to two locations.', 'Al volver, copiar ZIP y backup en dos lugares.')],
        chapter: 'lima', media: { category:'Lima', target:'malecon' }
      }
    }
  };
})();
