window.PERU_PHRASEBOOK = {
  categories: [
    { id: 'essential', pl: 'Najważniejsze', en: 'Essentials', es: 'Esenciales' },
    { id: 'transport', pl: 'Transport', en: 'Transport', es: 'Transporte' },
    { id: 'hotel', pl: 'Nocleg', en: 'Accommodation', es: 'Alojamiento' },
    { id: 'food', pl: 'Jedzenie', en: 'Food', es: 'Comida' },
    { id: 'health', pl: 'Zdrowie', en: 'Health', es: 'Salud' },
    { id: 'emergency', pl: 'Nagłe sytuacje', en: 'Emergencies', es: 'Emergencias' },
    { id: 'machu', pl: 'Machu Picchu', en: 'Machu Picchu', es: 'Machu Picchu' },
    { id: 'amazon', pl: 'Amazonia', en: 'Amazonia', es: 'Amazonía' },
    { id: 'money', pl: 'Zakupy i pieniądze', en: 'Shopping and money', es: 'Compras y dinero' }
  ],
  phrases: [
    ['hello','essential','Dzień dobry.','Hello.','Buenos días.'],
    ['thanks','essential','Dziękuję bardzo.','Thank you very much.','Muchas gracias.'],
    ['please','essential','Proszę.','Please.','Por favor.'],
    ['sorry','essential','Przepraszam.','Excuse me / I am sorry.','Disculpe / Lo siento.'],
    ['dont-understand','essential','Nie rozumiem.','I do not understand.','No entiendo.'],
    ['slower','essential','Czy może Pan/Pani mówić wolniej?','Could you speak more slowly?','¿Puede hablar más despacio?'],
    ['repeat','essential','Czy może Pan/Pani powtórzyć?','Could you repeat that?','¿Puede repetirlo?'],
    ['polish','essential','Mówimy po polsku i trochę po angielsku.','We speak Polish and a little English.','Hablamos polaco y un poco de inglés.'],
    ['show-phone','essential','Czy mogę pokazać to na telefonie?','May I show it on my phone?','¿Puedo mostrarlo en el teléfono?'],
    ['where-toilet','essential','Gdzie jest toaleta?','Where is the toilet?','¿Dónde está el baño?'],

    ['this-address','transport','Proszę zawieźć nas pod ten adres.','Please take us to this address.','Por favor, llévenos a esta dirección.'],
    ['how-much-ride','transport','Ile kosztuje przejazd dla trzech osób?','How much is the ride for three people?','¿Cuánto cuesta el viaje para tres personas?'],
    ['price-before','transport','Czy możemy ustalić cenę przed wyjazdem?','Can we agree on the price before leaving?','¿Podemos acordar el precio antes de salir?'],
    ['meter','transport','Proszę włączyć taksometr.','Please use the meter.','Por favor, use el taxímetro.'],
    ['wait-here','transport','Czy może Pan/Pani tutaj na nas poczekać?','Could you wait for us here?','¿Puede esperarnos aquí?'],
    ['stop-here','transport','Proszę zatrzymać się tutaj.','Please stop here.','Por favor, pare aquí.'],
    ['airport','transport','Jedziemy na lotnisko.','We are going to the airport.','Vamos al aeropuerto.'],
    ['station','transport','Jedziemy na stację kolejową w Ollantaytambo.','We are going to the train station in Ollantaytambo.','Vamos a la estación de tren de Ollantaytambo.'],
    ['three-tickets','transport','Poprosimy trzy bilety.','Three tickets, please.','Tres boletos, por favor.'],
    ['departure-time','transport','O której godzinie odjeżdża?','What time does it leave?','¿A qué hora sale?'],
    ['which-platform','transport','Z którego peronu lub stanowiska odjeżdża?','Which platform or bay does it leave from?','¿De qué andén o parada sale?'],
    ['luggage','transport','Czy możemy zostawić tutaj duże plecaki?','Can we leave our large backpacks here?','¿Podemos dejar aquí las mochilas grandes?'],

    ['reservation','hotel','Mamy rezerwację na nazwisko…','We have a reservation under the name…','Tenemos una reserva a nombre de…'],
    ['three-people','hotel','Jesteśmy w trzy osoby: para i jedna osoba osobno.','There are three of us: a couple and one separate guest.','Somos tres personas: una pareja y una persona por separado.'],
    ['checkin','hotel','Czy możemy już się zameldować?','Can we check in now?','¿Podemos hacer el check-in ahora?'],
    ['early-bags','hotel','Czy możemy zostawić bagaż przed zameldowaniem?','Can we leave our luggage before check-in?','¿Podemos dejar el equipaje antes del check-in?'],
    ['late-bags','hotel','Czy możemy odebrać bagaż wieczorem 20 września?','Can we collect the luggage on the evening of 20 September?','¿Podemos recoger el equipaje la noche del 20 de septiembre?'],
    ['hot-water','hotel','Nie ma ciepłej wody.','There is no hot water.','No hay agua caliente.'],
    ['wifi','hotel','Jakie jest hasło do Wi‑Fi?','What is the Wi-Fi password?','¿Cuál es la contraseña del Wi-Fi?'],
    ['quiet-room','hotel','Czy jest dostępny cichy pokój bez stromego podejścia?','Is a quiet room without a steep approach available?','¿Hay una habitación tranquila sin una subida pronunciada?'],
    ['wake-up','hotel','Czy możecie zamówić nam taxi na godzinę…?','Could you arrange a taxi for us at…?','¿Pueden pedirnos un taxi para las…?'],

    ['table-three','food','Stolik dla trzech osób, proszę.','A table for three, please.','Una mesa para tres, por favor.'],
    ['menu','food','Czy możemy prosić o menu?','Could we have the menu?','¿Nos trae la carta, por favor?'],
    ['cilantro','food','Bez kolendry, proszę.','No cilantro, please.','Sin cilantro, por favor.'],
    ['not-spicy','food','Proszę niezbyt ostre.','Not too spicy, please.','No muy picante, por favor.'],
    ['peanut','food','Czy to zawiera orzeszki ziemne?','Does this contain peanuts?','¿Esto contiene maní?'],
    ['vegetarian','food','Czy macie danie wegetariańskie?','Do you have a vegetarian dish?','¿Tienen un plato vegetariano?'],
    ['safe-water','food','Czy woda i lód są bezpieczne do picia?','Are the water and ice safe to drink?','¿El agua y el hielo son seguros para beber?'],
    ['bottled-water','food','Poprosimy wodę butelkowaną bez gazu.','Still bottled water, please.','Agua embotellada sin gas, por favor.'],
    ['bill','food','Poprosimy rachunek.','The bill, please.','La cuenta, por favor.'],
    ['separate-bill','food','Czy możemy zapłacić osobno?','Can we pay separately?','¿Podemos pagar por separado?'],
    ['card','food','Czy można zapłacić kartą?','Can we pay by card?','¿Se puede pagar con tarjeta?'],

    ['doctor','health','Potrzebuję lekarza.','I need a doctor.','Necesito un médico.'],
    ['ambulance','health','Proszę wezwać karetkę.','Please call an ambulance.','Por favor, llame a una ambulancia.'],
    ['breathing','health','Mam trudności z oddychaniem.','I am having difficulty breathing.','Tengo dificultad para respirar.'],
    ['altitude','health','Źle się czuję na wysokości: boli mnie głowa i mam nudności.','I feel unwell at altitude: I have a headache and nausea.','Me siento mal por la altura: tengo dolor de cabeza y náuseas.'],
    ['chest','health','Boli mnie w klatce piersiowej.','I have chest pain.','Me duele el pecho.'],
    ['allergy','health','Jestem uczulony/uczulona na…','I am allergic to…','Soy alérgico/alérgica a…'],
    ['medicine','health','Przyjmuję ten lek.','I take this medication.','Tomo este medicamento.'],
    ['diarrhea','health','Mam silną biegunkę i jestem odwodniony/odwodniona.','I have severe diarrhoea and I am dehydrated.','Tengo diarrea fuerte y estoy deshidratado/deshidratada.'],
    ['bite','health','Zostałem/zostałam ugryziony/ugryziona lub ukąszony/ukąszona.','I was bitten or stung.','Me mordió o me picó algo.'],
    ['when','health','Kiedy pojawiły się objawy?','When did the symptoms begin?','¿Cuándo comenzaron los síntomas?'],
    ['insurance','health','Mamy ubezpieczenie podróżne.','We have travel insurance.','Tenemos seguro de viaje.'],

    ['police','emergency','Potrzebujemy policji.','We need the police.','Necesitamos a la policía.'],
    ['passport-lost','emergency','Zgubiłem/zgubiłam paszport.','I lost my passport.','Perdí mi pasaporte.'],
    ['phone-stolen','emergency','Skradziono mi telefon.','My phone was stolen.','Me robaron el teléfono.'],
    ['wallet-stolen','emergency','Skradziono mi portfel i karty.','My wallet and cards were stolen.','Me robaron la cartera y las tarjetas.'],
    ['help-now','emergency','Potrzebujemy natychmiastowej pomocy.','We need help immediately.','Necesitamos ayuda inmediatamente.'],
    ['location','emergency','Jesteśmy w tym miejscu.','We are at this location.','Estamos en este lugar.'],
    ['three-safe','emergency','Jesteśmy w trzy osoby. Czy wszyscy są bezpieczni?','There are three of us. Is everyone safe?','Somos tres personas. ¿Todos están a salvo?'],

    ['cultural-centre','machu','Gdzie jest Centro Cultural de Machu Picchu?','Where is the Machu Picchu Cultural Centre?','¿Dónde está el Centro Cultural de Machu Picchu?'],
    ['buy-circuit','machu','Chcemy kupić trzy bilety na Circuito 2, Ruta 2-A lub 2-B, na 20 września.','We want to buy three tickets for Circuit 2, Route 2-A or 2-B, for 20 September.','Queremos comprar tres boletos para el Circuito 2, Ruta 2-A o 2-B, para el 20 de septiembre.'],
    ['priority-time','machu','Najlepiej na godzinę 13:00, a jeśli nie ma miejsc, na 14:00.','Preferably for 13:00; if unavailable, for 14:00.','Preferiblemente para las 13:00; si no hay disponibilidad, para las 14:00.'],
    ['route-ticket','machu','Mamy bilety na Rutę 3-A Waynapicchu na 07:00.','We have tickets for Route 3-A Waynapicchu at 07:00.','Tenemos boletos para la Ruta 3-A Waynapicchu a las 07:00.'],
    ['correct-line','machu','Czy to jest właściwa kolejka dla Ruty 3-A?','Is this the correct queue for Route 3-A?','¿Esta es la cola correcta para la Ruta 3-A?'],
    ['last-bus','machu','O której odjeżdża ostatni autobus do Aguas Calientes?','What time is the last bus to Aguas Calientes?','¿A qué hora sale el último autobús a Aguas Calientes?'],
    ['train-time','machu','Mamy pociąg z Ollantaytambo o 20:50.','We have a train from Ollantaytambo at 20:50.','Tenemos un tren desde Ollantaytambo a las 20:50.'],

    ['quiet','amazon','Proszę o ciszę — obserwujemy zwierzę.','Please be quiet — we are watching an animal.','Silencio, por favor: estamos observando un animal.'],
    ['which-species','amazon','Jaki to gatunek?','What species is this?','¿Qué especie es?'],
    ['write-name','amazon','Czy może Pan/Pani zapisać nazwę gatunku?','Could you write down the species name?','¿Puede escribir el nombre de la especie?'],
    ['animal-distance','amazon','Proszę nie podchodzić bliżej do zwierzęcia.','Please do not move closer to the animal.','Por favor, no se acerque más al animal.'],
    ['camping','amazon','Chcemy intensywny program terenowy i prawdziwy camping, jeśli warunki są bezpieczne.','We want an intensive field programme and genuine camping if conditions are safe.','Queremos un programa de campo intenso y un campamento auténtico si las condiciones son seguras.'],
    ['water-level','amazon','Jaki jest dzisiaj poziom wody i gdzie są największe szanse na zwierzęta?','What is the water level today and where are the best wildlife chances?','¿Cuál es el nivel del agua hoy y dónde hay más posibilidades de ver animales?'],
    ['rain','amazon','Czy przez pogodę musimy zmienić plan?','Do we need to change the plan because of the weather?','¿Tenemos que cambiar el plan por el tiempo?'],
    ['return-lodge','amazon','Musimy wrócić do lodge.','We need to return to the lodge.','Tenemos que volver al lodge.'],

    ['how-much','money','Ile to kosztuje?','How much does it cost?','¿Cuánto cuesta?'],
    ['too-expensive','money','To za drogo. Jaka jest najlepsza cena?','That is too expensive. What is your best price?','Es demasiado caro. ¿Cuál es su mejor precio?'],
    ['cash-card','money','Gotówka czy karta?','Cash or card?','¿Efectivo o tarjeta?'],
    ['receipt','money','Poproszę paragon lub potwierdzenie.','A receipt or confirmation, please.','Un recibo o comprobante, por favor.'],
    ['change','money','Czy ma Pan/Pani wydać z tej kwoty?','Do you have change for this amount?','¿Tiene cambio para este monto?'],
    ['three-items','money','Chcemy kupić trzy sztuki.','We want to buy three items.','Queremos comprar tres unidades.']
  ].map(([id, category, pl, en, es]) => ({ id, category, pl, en, es }))
};
